<Project>

    <!-- fkelava 30/09/25 23:05
    https://github.com/dotnet/sdk/issues/1366

    Mods must not include any Fahrenheit core or mod libraries in their build output.
    The SDK ensures this- and so must the user- by structuring <ProjectReference>s as such:

    <ProjectReference Include="...">
        <Private>false</Private>
        <ExcludeAssets>runtime;native</ExcludeAssets>
    </ProjectReference>

    However, in the transitive case where a mod references a mod, MSBuild will fail to
    respect the chain of ExcludeAssets tags and emit Fahrenheit libraries alongside
    the mod, which is invalid and will cause issues. This target solves that problem.
    -->
    <Target Name="__FhMakeTransitiveProjectRefsNonPrivate" AfterTargets="IncludeTransitiveProjectReferences">
        <ItemGroup>
            <!-- remove the transitive project references and re-add them as non-private project references -->
            <ProjectReference Remove="@(_TransitiveProjectReferences)" />
            <ProjectReference Include="@(_TransitiveProjectReferences)" Private="False" />
        </ItemGroup>
    </Target>
    
    <!-- fkelava 21/07/26 00:25
    https://github.com/dotnet/sdk/issues/42153
    
    We no longer build everything for `win-x86`, but instead support three RIDs: `win-x86`, `win-x64`, `linux-x64`.
    Each project specifies its supported RIDs with <RuntimeIdentifiers>. But the SDK doesn't use that to filter
    the native DLLs it will output; it's just a hint for NuGet package restore purposes.
    
    This target serves to accomplish that purpose so we don't ship DLLs for platforms we don't support.
    -->
    <Target Name="FilterRuntimeTargetItems" AfterTargets="ResolvePackageAssets" BeforeTargets="ResolveLockFileReferences">
        <ItemGroup>
            <_AssetFilteringRids Include="win-x86;win-x64;linux-x64" />
        </ItemGroup>
        
        <!-- Invoke SelectRuntimeIdentifierSpecificItems for each filtering RID to get just the items that are compatible with that RID -->
        <SelectRuntimeIdentifierSpecificItems 
            Items="@(RuntimeTargetsCopyLocalItems)"
            TargetRuntimeIdentifier="%(_AssetFilteringRids.Identity)"
            RuntimeIdentifierGraphPath="$(RuntimeIdentifierGraphPath)" >
            
            <Output TaskParameter="SelectedItems" ItemName="_FilteredRuntimeTargetsCopyLocalItems" />
        </SelectRuntimeIdentifierSpecificItems>
        
        <ItemGroup>
            <RuntimeTargetsCopyLocalItems Remove="@(RuntimeTargetsCopyLocalItems)" />
            <RuntimeTargetsCopyLocalItems Include="@(_FilteredRuntimeTargetsCopyLocalItems)" />
        </ItemGroup>
    </Target>

    <!-- fkelava 09/06/26 17:36
    A placeholder target to force publishing to occur after a build.
    Publishing places build output in its proper place.
    -->
    <Target Name="__FhPublishAfterBuild" AfterTargets="Build" DependsOnTargets="Publish" />

</Project>
