/* [fkelava 9/5/23 23:37]
 * source: MS Store ver.
 * header: __BATTLE_ATEL__
 *
 * /ffx_ps2/ffx2/master/jppc/battle/header/btlhead.src
 *
 * Partial. Many constants yet to come along with other stuff.
 */

namespace Fahrenheit.CoreLib.FFX2;

public enum ChrStatId : T_X2ChrStatId {
    STAT_NOP                       = 0,  // なし
    STAT_HP                        = 1,  // ＨＰ
    STAT_MP                        = 2,  // ＭＰ
    STAT_MAXHP                     = 3,  // 最大ＨＰ
    STAT_MAXMP                     = 4,  // 最大ＭＰ
    STAT_WEAK                      = 5,  // 弱り
    STAT_INBATTLE                  = 6,  // バトルに出ているフラグ
    STAT_MAN                       = 7,  // 男フラグ
    STAT_FEMALE                    = 8,  // 女フラグ
    STAT_MONSTER                   = 9,  // モンスターフラグ
    STAT_FLY                       = 10, // 飛んでるフラグ
    STAT_STR                       = 11, // 力
    STAT_VIT                       = 12, // 体力
    STAT_MAG                       = 13, // 魔力
    STAT_SPIRIT                    = 14, // 精神
    STAT_DEX                       = 15, // すばやさ
    STAT_LUCK                      = 16, // 運
    STAT_AVOID                     = 17, // 回避率
    STAT_HIT                       = 18, // 命中率
    STAT_STR_ADJUST                = 19, // 力：調整値
    STAT_VIT_ADJUST                = 20, // 体力：調整値
    STAT_MAG_ADJUST                = 21, // 魔力：調整値
    STAT_SPIRIT_ADJUST             = 22, // 精神：調整値
    STAT_DEX_ADJUST                = 23, // すばやさ：調整値
    STAT_LUCK_ADJUST               = 24, // 運：調整値
    STAT_AVOID_ADJUST              = 25, // 回避率：調整値
    STAT_HIT_ADJUST                = 26, // 命中率：調整値
    STAT_ABS_FIRE                  = 27, // 吸収属性 炎
    STAT_ABS_COLD                  = 28, // 吸収属性 冷気
    STAT_ABS_THUNDER               = 29, // 吸収属性 雷
    STAT_ABS_WATER                 = 30, // 吸収属性 水
    STAT_ABS_HOLY                  = 31, // 吸収属性 聖
    STAT_ABS_GRAVITY               = 32, // 吸収属性 重力
    STAT_INV_FIRE                  = 33, // 無効属性 炎
    STAT_INV_COLD                  = 34, // 無効属性 冷気
    STAT_INV_THUNDER               = 35, // 無効属性 雷
    STAT_INV_WATER                 = 36, // 無効属性 水
    STAT_INV_HOLY                  = 37, // 無効属性 聖
    STAT_INV_GRAVITY               = 38, // 無効属性 重力
    STAT_HALF_FIRE                 = 39, // 半減属性 炎
    STAT_HALF_COLD                 = 40, // 半減属性 冷気
    STAT_HALF_THUNDER              = 41, // 半減属性 雷
    STAT_HALF_WATER                = 42, // 半減属性 水
    STAT_HALF_HOLY                 = 43, // 半減属性 聖
    STAT_HALF_GRAVITY              = 44, // 半減属性 重力
    STAT_WEAK_FIRE                 = 45, // 弱点属性 炎
    STAT_WEAK_COLD                 = 46, // 弱点属性 冷気
    STAT_WEAK_THUNDER              = 47, // 弱点属性 雷
    STAT_WEAK_WATER                = 48, // 弱点属性 水
    STAT_WEAK_HOLY                 = 49, // 弱点属性 聖
    STAT_WEAK_GRAVITY              = 50, // 弱点属性 重力
    STAT_POISON_PER                = 51, // 毒ダメージ割合
    STAT_AREA                      = 52, // 立ち位置エリア
    STAT_POS                       = 53, // 立ち位置番号
    STAT_GROUP                     = 54, // グループフラグ
    STAT_ALIVE                     = 55, // 戦闘可能
    STAT_STONE                     = 56, // 石化
    STAT_SLEEP                     = 57, // 睡眠
    STAT_SILENCE                   = 58, // 沈黙
    STAT_DARK                      = 59, // 暗闇
    STAT_POISON                    = 60, // 毒
    STAT_CONFUSE                   = 61, // こんらん
    STAT_BERSERK                   = 62, // バーサク
    STAT_CURSE                     = 63, // カーズ
    STAT_DEFENSE                   = 64, // ぼうぎょ
    STAT_BLOW                      = 65, // 吹き飛ばし
    STAT_HP_DOUBLE                 = 66, // ＨＰ２倍
    STAT_MP_DOUBLE                 = 67, // ＭＰ２倍
    STAT_USE_MP0                   = 68, // 消費ＭＰ０
    STAT_DAMAGE9999                = 69, // ダメージ９９９９
    STAT_ABS_CRITICAL              = 70, // 絶対クリティカル
    STAT_EXP0                      = 71, // 経験値０
    STAT_CHANGE_CLOTH              = 72, // 着替えたい
    STAT_RELIFE                    = 73, // リレイズ
    STAT_SHELL                     = 74, // シェル
    STAT_PROTESS                   = 75, // プロテス
    STAT_REFLECT                   = 76, // リフレク
    STAT_REGEN                     = 77, // リジェネ
    STAT_HASTE                     = 78, // へイスト
    STAT_SLOW                      = 79, // スロウ
    STAT_STOP                      = 80, // ストップ
    STAT_STR_CHANGE                = 81, // 攻撃調整
    STAT_MAG_CHANGE                = 82, // 魔法調整
    STAT_VIT_CHANGE                = 83, // 防御調整
    STAT_SPIRIT_CHANGE             = 84, // 魔法防御調整
    STAT_HIT_CHANGE                = 85, // 命中アップ調整
    STAT_LUCK_CHANGE               = 86, // 運アップ調整
    STAT_DEATH_SENTENCE            = 87, // 死の宣告
    STAT_INVINCIBLE_PHYSIC         = 88, // 物理無効
    STAT_INVINCIBLE_MAGIC          = 89, // 魔法無効
    STAT_INVINCIBLE                = 90, // 無敵
    STAT_AUTO_ALIVE                = 91, // 戦闘可能
    STAT_AUTO_STONE                = 92, // 石化
    STAT_AUTO_SLEEP                = 93, // 睡眠
    STAT_AUTO_SILENCE              = 94, // 沈黙
    STAT_AUTO_DARK                 = 95, // 暗闇
    STAT_AUTO_POISON               = 96, // 毒
    STAT_AUTO_CONFUSE              = 97, // こんらん
    STAT_AUTO_BERSERK              = 98, // バーサク
    STAT_AUTO_CURSE                = 99, // カーズ
    STAT_AUTO_DEFENSE              = 100, // ぼうぎょ
    STAT_AUTO_BLOW                 = 101, // 吹き飛ばし
    STAT_AUTO_HP_DOUBLE            = 102, // ＨＰ２倍
    STAT_AUTO_MP_DOUBLE            = 103, // ＭＰ２倍
    STAT_AUTO_USE_MP0              = 104, // 消費ＭＰ０
    STAT_AUTO_DAMAGE9999           = 105, // ダメージ９９９９
    STAT_AUTO_ABS_CRITICAL         = 106, // 絶対クリティカル
    STAT_AUTO_EXP0                 = 107, // 経験値０
    STAT_AUTO_CHANGE_CLOTH         = 108, // 着替えたい
    STAT_AUTO_RELIFE               = 109, // リレイズ
    STAT_AUTO_SHELL                = 110, // シェル
    STAT_AUTO_PROTESS              = 111, // プロテス
    STAT_AUTO_REFLECT              = 112, // リフレク
    STAT_AUTO_REGEN                = 113, // リジェネ
    STAT_AUTO_HASTE                = 114, // へイスト
    STAT_AUTO_SLOW                 = 115, // スロウ
    STAT_AUTO_STOP                 = 116, // ストップ
    STAT_AUTO_STR_CHANGE           = 117, // 攻撃調整
    STAT_AUTO_MAG_CHANGE           = 118, // 魔法調整
    STAT_AUTO_VIT_CHANGE           = 119, // 防御調整
    STAT_AUTO_SPIRIT_CHANGE        = 120, // 魔法防御調整
    STAT_AUTO_HIT_CHANGE           = 121, // 命中アップ調整
    STAT_AUTO_LUCK_CHANGE          = 122, // 運アップ調整
    STAT_AUTO_DEATH_SENTENCE       = 123, // 死の宣告
    STAT_AUTO_INVINCIBLE_PHYSIC    = 124, // 物理無効
    STAT_AUTO_INVINCIBLE_MAGIC     = 125, // 魔法無効
    STAT_AUTO_INVINCIBLE           = 126, // 無敵
    STAT_DEF_DEATH                 = 127, // 防御:戦闘不能
    STAT_DEF_STONE                 = 128, // 防御:石化
    STAT_DEF_SLEEP                 = 129, // 防御:睡眠
    STAT_DEF_SILENCE               = 130, // 防御:沈黙
    STAT_DEF_DARK                  = 131, // 防御:暗闇
    STAT_DEF_POISON                = 132, // 防御:毒
    STAT_DEF_CONFUSE               = 133, // 防御:こんらん
    STAT_DEF_BERSERK               = 134, // 防御:バーサク
    STAT_DEF_CURSE                 = 135, // 防御:カーズ
    STAT_DEF_DEFENSE               = 136, // 防御:ぼうぎょ
    STAT_DEF_BLOW                  = 137, // 防御:吹き飛ばし
    STAT_DEF_HP_DOUBLE             = 138, // 防御:ＨＰ２倍
    STAT_DEF_MP_DOUBLE             = 139, // 防御:ＭＰ２倍
    STAT_DEF_USE_MP0               = 140, // 防御:消費ＭＰ０
    STAT_DEF_DAMAGE9999            = 141, // 防御:ダメージ９９９９
    STAT_DEF_ABS_CRITICAL          = 142, // 防御:絶対クリティカル
    STAT_DEF_EXP0                  = 143, // 防御:経験値０
    STAT_DEF_CHANGE_CLOTH          = 144, // 防御:着替えたい
    STAT_DEF_RELIFE                = 145, // 防御:リレイズ
    STAT_DEF_SHELL                 = 146, // 防御:シェル
    STAT_DEF_PROTESS               = 147, // 防御:プロテス
    STAT_DEF_REFLECT               = 148, // 防御:リフレク
    STAT_DEF_REGEN                 = 149, // 防御:リジェネ
    STAT_DEF_HASTE                 = 150, // 防御:へイスト
    STAT_DEF_SLOW                  = 151, // 防御:スロウ
    STAT_DEF_STOP                  = 152, // 防御:ストップ
    STAT_DEF_STR_CHANGE            = 153, // 防御:攻撃調整
    STAT_DEF_MAG_CHANGE            = 154, // 防御:魔法調整
    STAT_DEF_VIT_CHANGE            = 155, // 防御:防御調整
    STAT_DEF_SPIRIT_CHANGE         = 156, // 防御:魔法防御調整
    STAT_DEF_HIT_CHANGE            = 157, // 防御:命中調整
    STAT_DEF_LUCK_CHANGE           = 158, // 防御:運調整
    STAT_DEF_DEATH_SENTENCE        = 159, // 防御:死の宣告
    STAT_DEF_INVINCIBLE_PHYSIC     = 160, // 防御:物理無効
    STAT_DEF_INVINCIBLE_MAGIC      = 161, // 防御:魔法無効
    STAT_DEF_INVINCIBLE            = 162, // 防御:無敵
    STAT_SP_MAGIC_CANCEL           = 163, // 魔法キャンセル不可
    STAT_SP_WAIRO                  = 164, // わいろ不可
    STAT_SP_DISABLE_ZAN            = 165, // 斬魔刀で切れないフラグ
    STAT_SP_INVINCIBLE             = 166, // 無敵
    STAT_SP_INV_MAGIC              = 167, // 魔法無効
    STAT_SP_INV_PHYSIC             = 168, // 物理無効
    STAT_SP_INV_ATB                = 169, // ATB 無効
    STAT_SP_LIVE                   = 170, // ライブラフラグ
    STAT_SP_RATIO                  = 171, // 割合ダメージフラグ
    STAT_SP_DAMAGE_NOT_STOP        = 172, // ダメージ時に時間が止まらないフラグ
    STAT_EXP                       = 173, // 獲得：経験値
    STAT_GET_AP                    = 174, // 獲得：ＡＰ
    STAT_GILL                      = 175, // 獲得：ギル
    STAT_STEAL_GILL                = 176, // 盗むギル
    STAT_DROP                      = 177, // 通常アイテム落とす確率
    STAT_STEAL                     = 178, // 盗む確率
    STAT_STEAL_COUNT               = 179, // 盗まれカウント
    STAT_DROP_ITEM                 = 180, // 落とすアイテム
    STAT_DROP_ITEM_NUM             = 181, // 落とすアイテム数
    STAT_DROP_RARE_ITEM            = 182, // 落とすレアアイテム
    STAT_DROP_RARE_ITEM_NUM        = 183, // 落とすレアアイテム数
    STAT_STEAL_ITEM                = 184, // 盗めるアイテム
    STAT_STEAL_ITEM_NUM            = 185, // 盗めるアイテム数
    STAT_STEAL_RARE_ITEM           = 186, // 盗めるレアアイテム
    STAT_STEAL_RARE_ITEM_NUM       = 187, // 盗めるレアアイテム数
    STAT_BRIBERY_ITEM              = 188, // わいろアイテム
    STAT_BRIBERY_ITEM_NUM          = 189, // わいろアイテム数
    STAT_BRIBERY_RARE_ITEM         = 190, // わいろレアアイテム
    STAT_BRIBERY_RARE_ITEM_NUM     = 191, // わいろレアアイテム数
    STAT_APPEAR_COUNT              = 192, // 出現カウント
    STAT_ATTACK_NORMAL_FRAME       = 193, // 攻撃通常フレーム数
    STAT_MOTION_NUM                = 194, // モーション補間番号
    STAT_ATTACK_INC_SPEED          = 195, // 攻撃：加速％
    STAT_ATTACK_DEC_SPEED          = 196, // 攻撃：減速％
    STAT_ROUND                     = 197, // 通常方向フレーム
    STAT_DIRECTION_CHANGE_FLAG     = 198, // 方向変更フラグ
    STAT_DIRECTION_CHANGE_EFFECT   = 199, // 方向変更有効フラグ
    STAT_DIRECTION_FIX_FLAG        = 200, // 方向固定フラグ
    STAT_WIN_SE                    = 201, // 勝利のＳＥ
    STAT_EFFECT_HIT_NUM            = 202, // ヒットエフェクト番号
    STAT_MOTION_TYPE               = 203, // モーションタイプ
    STAT_ATTACK_MOTION_TYPE        = 204, // 攻撃モーションタイプ
    STAT_IDLE2_PROB                = 205, // アイドリング２確率
    STAT_HIDE                      = 206, // ハイド
    STAT_DISABLE_MOVE_FLAG         = 207, // 移動不可フラグ
    STAT_DISABLE_JUMP_FLAG         = 208, // ジャンプ不可フラグ
    STAT_BODYHIT_FLAG              = 209, // 体の当たり判定
    STAT_EFFECT_TARGET_FLAG        = 210, // エフェクトのターゲットフラグ
    STAT_DEATH_PATTERN             = 211, // 死にパターン
    STAT_DAMAGE_CHR                = 212, // ダメージを受けるキャラクター
    STAT_DAMAGE_HP                 = 213, // ＨＰダメージ
    STAT_DAMAGE_MP                 = 214, // ＭＰダメージ
    STAT_DAMAGE_ATB                = 215, // ＡＴＢダメージ
    STAT_CURSOR                    = 216, // カーソルフラグ
    STAT_CURSOR_ELEMENT            = 217, // カーソルエレメント
    STAT_VISIBLE                   = 218, // 表示フラグ
    STAT_VISIBLE_CAM               = 219, // カメラ用表示フラグ
    STAT_VISIBLE_EFF               = 220, // エフェクト用表示フラグ
    STAT_EFFVAR                    = 221, // エフェクト変数
    STAT_EFFLV                     = 222, // エフェクトレベル
    STAT_MOTIONLV                  = 223, // モーションレベル
    STAT_EXIST_FLAG                = 224, // 存在フラグ
    STAT_OWN_REACTION_AMOUNT       = 225, // 自分の指定キャラへのリアクションコマンドの数を調べる
    STAT_REACTION_AMOUNT           = 226, // 指定キャラのリアクションコマンドの数を調べる
    STAT_DISTANCE2D                = 227, // 距離XZ
    STAT_DISTANCE                  = 228, // 距離XYZ
    STAT_ATB_REST                  = 229, // 残りATB 値
    STAT_ATB_REST_SET              = 230, // 残りATB 設定値
    STAT_CHANT_REST                = 231, // 残り詠唱値
    STAT_CHANT_REST_SET            = 232, // 残り詠唱設定値
    STAT_CHANT_MAGIC               = 233, // 魔法中かどうかチェックする
    STAT_ACTION                    = 234, // 行動フラグ
    STAT_HP_LIST                   = 235, // ＨＰリスト表示
    STAT_APPEAR_MOTION_FLAG        = 236, // 出現モーションフラグ
    STAT_BLOW_EXIST_FLAG           = 237, // 吹き飛ばし＝存在フラグ
    STAT_ESCAPE_FLAG               = 238, // 逃げるフラグ
    STAT_WIN_POSE                  = 239, // 勝利のポーズを取るフラグ
    STAT_DEATH                     = 240, // 死亡
    STAT_DEATH_STONE               = 241, // 死亡か石化
    STAT_CAM_WIDTH                 = 242, // カメラの太さ
    STAT_CAM_HEIGHT                = 243, // カメラの高さ
    STAT_WIDTH                     = 244, // 幅
    STAT_HEIGHT                    = 245, // 高さ
    STAT_MOVE_START_MODE           = 246, // 移動開始モード
    STAT_MOVE_END_MODE             = 247, // 移動終了モード
    STAT_MOVE_END_DIST             = 248, // 移動終了距離
    STAT_MOVE_START_TARGET_BIT     = 249, // 移動開始のターゲットビット
    STAT_MOVE_END_TARGET_BIT       = 250, // 移動終了のターゲットビット
    STAT_JOIN                      = 251, // 仲間になっている判定
    STAT_NECK_TARGET_FLAG          = 252, // 首ターゲットなし
    STAT_CHAIN_COUNT               = 253, // 連鎖カウント
    STAT_BACKDAMAGE_FLAG           = 254, // 後ろからのダメージフラグ
    STAT_DEATH_STATUS              = 255, // 死亡ステータス
    STAT_TARGET_LIST               = 256, // ターゲットリストフラグ
    STAT_AUTO_CAMERA_FLAG          = 257, // 自動カメラターゲットに含めるフラグ
    STAT_AUTO_POS_FLAG             = 258, // 自動立ち位置に含めるフラグ
    STAT_WEAPON_FLAG               = 259, // 武器フラグ
    STAT_DIR_REVERSE_FLAG          = 260, // 次発行モーションで方向１８０度変更フラグ
    STAT_RETURN_FLAG               = 261, // 戻りフラグ：調教師用
    STAT_COMMAND_TYPE              = 262, // コマンドタイプ：モーションアンカー用
    STAT_ALIVE_NOT_STONE           = 263, // 生きていて石化でない
    STAT_WEAPON_ATTACH_FLAG        = 264, // 武器のアタッチ可能フラグ：調教師用
    STAT_BEFORE_JOB                = 265, // 変身前のジョブ番号
    STAT_AFTER_JOB                 = 266, // 変身後のジョブ番号
    STAT_EXE_COMMAND               = 267, // 最後に実行したコマンド
    STAT_ICON_NUMBER               = 268, // アイコン番号
    STAT_OVERSOUL                  = 269, // オーバーソウル状態かどうか
    STAT_OVERSOUL_TYPE             = 270, // オーバーソウルタイプ
    STAT_OVERSOUL_COUNT            = 271, // オーバーソウルカウント
    STAT_OVERSOUL_COUNT_MAX        = 272, // オーバーソウルカウント最大値
    STAT_OVERSOULED                = 273, // オーバーソウルしたことがあるフラグ
    STAT_HP_CHECK                  = 274, // ＨＰが満タンかチェック
    STAT_HP_HALF                   = 275, // ＨＰ1/2以下チェック
    STAT_HP_QUARTER                = 276, // ＨＰ1/4以下チェック
    STAT_MP_CHECK                  = 277, // ＭＰが満タンかチェック
    STAT_DANCING                   = 278, // 踊っているフラグ
    STAT_ON_CACHE_FLAG             = 279, // キャッシュに乗っているフラグ
    STAT_MENU_CANCEL_FLAG          = 280, // メニューでのキャンセル可能フラグ
    STAT_DRESS_UP_FLAG             = 281, // ドレスアップ可能フラグ
    ABILITY_LEAD                   = 282, // さきがけ
    ABILITY_FIRST                  = 283, // せんせい
    ABILITY_COUNTER                = 284, // カウンター
    ABILITY_COUNTER2               = 285, // カウンター２
    ABILITY_MAGIC_COUNTER          = 286, // 魔法カウンター
    ABILITY_BOOSTER                = 287, // 魔法ブースター:リレイズを除く
    ABILITY_MORE_ENCOUNT           = 288, // エンカウントを増やす
    ABILITY_MAGIC                  = 289, // 魔力剣
    ABILITY_MEDICINE               = 290, // くすりのちしき
    ABILITY_ELEMENT_MASTER         = 291, // ６属性の知識
    ABILITY_NON_ELEMENT_MASTER     = 292, // 無属性の知識
    ABILITY_STATUS_MASTER          = 293, // ST変化の知識
    ABILITY_AP_DOUBLE              = 294, // ＡＰ２倍:本人だけ
    ABILITY_AP_TRIPLE              = 295, // ＡＰ３倍:本人だけ
    ABILITY_HP_TOPPA               = 296, // ＨＰげんかいとっぱ
    ABILITY_MP_TOPPA               = 297, // ＭＰげんかいとっぱ
    ABILITY_DMG_TOPPA              = 298, // ダメージ限界突破
    ABILITY_RAREITEM_ONLY          = 299, // レアアイテムのみ
    ABILITY_DRAIN_SWORD            = 300, // ドレイン剣
    ABILITY_ASPIL_SWORD            = 301, // アスピル剣
    ABILITY_GILL_DOUBLE            = 302, // ギル２倍:３人つけると８倍
    ABILITY_ITEM_DOUBLE            = 303, // アイテム２倍:３人つけると８倍
    ABILITY_EXP_DOUBLE             = 304, // ＥＸＰ２倍:本人だけ
    ABILITY_AUTO_HP                = 305, // 自動ＨＰ回復
    ABILITY_AUTO_MP                = 306, // 自動ＭＰ回復
    ABILITY_PROBABILITY_UP         = 307, // 落とす確率アップ:３人つけるとさらにアップ
    ABILITY_REFLECT_PIERCE         = 308, // リフレク貫通
    ABILITY_HP_RECOVER             = 309, // 歩くとＨＰ回復
    ABILITY_MP_RECOVER             = 310, // 歩くとＭＰ回復
    ABILITY_NONENCOUNT             = 311, // エンカウントなし
    ABILITY_SHOOT_LV2              = 312, // 連射ＬＶ．２
    ABILITY_SHOOT_LV3              = 313, // 連射ＬＶ．３
    ABILITY_LIBRA_LV2              = 314, // みやぶるＬＶ２
    ABILITY_LIBRA_LV3              = 315, // みやぶるＬＶ３
    ABILITY_MP_HALF                = 316, // ＭＰ消費１／２
    ABILITY_MP_1                   = 317, // ＭＰ消費１
    STAT_TALK_STAT1                = 318, // 喋れる状態１
    STAT_TALK_STAT2                = 319, // 喋れる状態２
    STAT_TALK_STAT3                = 320, // 喋れる状態３
    STAT_TALK_STAT4                = 321, // 喋れる状態４
    STAT_SHELL_REFLECT             = 322, // シェルかリフレクがかかっている
    STAT_PROTESS_REFLECT           = 323, // プロテスかリフレクがかかっている
    STAT_HASTE_REFLECT             = 324, // ヘイストかリフレクがかかっている
    STAT_HIT_EFFECT_OFF_FLAG       = 325, // ２回ヒットエフェクトを出さないフラグ
    STAT_RAPID_SHOT_STATUS         = 326, // 速射ステータス
    STAT_FADEOUT                   = 327, // 外に出す時フェードアウト必要
    STAT_WEAK_MOTION               = 328, // 弱りモーションの取得
    STAT_SHADOW                    = 329, // 影フラグ
    STAT_DMG_DIR                   = 330, // ダメージ方向
    STAT_APPEAR_INVISIBLE_FLAG     = 331, // 出現時見えないフラグ
    STAT_MODEL                     = 332, // モデルフラグ
    STAT_INV_PHYSIC_MOTION         = 333, // 物理無効モーションフラグ
    STAT_INV_MAGIC_MOTION          = 334, // 魔法無効モーションフラグ
    STAT_VIGOR                     = 335, // 元気状態を得る
    STAT_SOUND_HIT_NUM_CRITICAL    = 336, // クリティカルヒットＳＥ番号
    STAT_MAGIC_EFFECT_GROUND       = 337, // 地上：魔法エフェクト番号
    STAT_MAGIC_EFFECT_WATER        = 338, // 水中：魔法エフェクト番号
    STAT_INFO_MES_ID               = 339, // 情報メッセージＩＤ
    STAT_LIVE_MES_ID               = 340, // ライブラメッセージＩＤ
    STAT_MOTION_SPEED_NORMAL       = 341, // 通常モーションスピード
    STAT_MOTION_SPEED_NORMAL_START = 342, // 通常モーションスピード：モーション開始時
    STAT_COMMAND_SET               = 343, // コマンド設定可能状態
    STAT_SOUND_HIT_NUM             = 344, // ヒットＳＥ番号
    STAT_DAMAGE_NUM_POS            = 345, // ダメージ数値位置
    STAT_MOTION_TYPE_RESET         = 346, // モーションタイプリセット
    STAT_MOTION_TYPE_ADD           = 347, // モーションタイプ追加
    STAT_SAME_TARGET_CHECK         = 348, // 同じターゲットチェック
    STAT_BODYHIT_DIRECT            = 349, // 直接ボディヒット設定
    STAT_NUM_PRINT_ELEMENT         = 350, // 番号表示エレメント
    STAT_MOTION_TYPE_MONSTER       = 351, // モンスターモーションタイプ
    STAT_PLAYER_NAME               = 352, // プレイヤーネームフラグ
    STAT_DIST                      = 353, // 遠距離、近距離フラグ
    STAT_SPECIAL_JOB               = 354, // 究極着替えフラグ
    STAT_TITLE_POS                 = 355, // タイトル位置
    STAT_LEVEL                     = 356, // レベル
    STAT_LEVEL_MAX                 = 357, // レベル最大値
    STAT_NO_DAMAGE_EXE_FLAG        = 358, // タグ実行中ダメージなしフラグ
    STAT_CHANGE_MOTION_NUM         = 359, // 着替えモーション番号
    STAT_FRIEND_MONSTER            = 360, // 仲間モンスター
    STAT_INBATTLE_PLAYER           = 361, // 指定プレイヤーキャラが捕獲モンスターでなくバトルに参加している
    STAT_WEAK_LEVEL_MASK           = 362, // 弱りマスクの設定
    STAT_DEATH_PATTERN_FRIEND      = 363, // 死にパターン：捕獲モンスター
    STAT_MOTION_IDLE_TYPE          = 364, // アイドリングモーションタイプ
}