<Project>
    <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />

    <!-- fkelava 30/09/25 23:05
    https://github.com/dotnet/sdk/issues/1366

    Mods must not include any Fahrenheit core or mod libraries in their build output.
    The SDK ensures this- and so must the user- by structuring <ProjectReference>s as such:

    <ProjectReference Include="...">
        <Private>false</Private>
        <ExcludeAssets>runtime;native</ExcludeAssets>
    </ProjectReference>

    However, in the transitive case where a mod references a mod, MSBuild will fail to
    respect the chain of ExcludeAssets tags and emit Fahrenheit libraries alongside
    the mod, which is invalid and will cause issues. This target solves that problem.
    -->
    <Target Name="_FhMakeTransitiveProjectRefsNonPrivate" AfterTargets="IncludeTransitiveProjectReferences">
        <ItemGroup>
            <!-- remove the transitive project references and re-add them as non-private project references -->
            <ProjectReference Remove="@(_TransitiveProjectReferences)" />
            <ProjectReference Include="@(_TransitiveProjectReferences)" Private="False" />
        </ItemGroup>
    </Target>

    <!-- fkelava 09/06/26 17:36
    A placeholder target to force publishing to occur after a build.
    Publishing places build output in its proper place.
    -->
    <Target Name="_FhPublishAfterBuild" AfterTargets="Build" DependsOnTargets="Publish" />

</Project>
