namespace Fahrenheit.CoreLib.FFX;

/* [fkelava 7/5/23 13:14]
 * Located in the executable at +852E00h.
 * 
 * This discovery was originally made by ffgriever (https://gitlab.com/ffgriever). These definitions are taken from his code wholesale.
 * 
 * Without his help and patient explanations, I would not have even the slightest understanding of FFX/X-2 scripting.
 */

public sealed record VMInstruction(string Name, uint OperandType, uint OperandCount, ushort InsnSize, ushort __UNKNOWN1);

public static partial class VM {
    public static readonly VMInstruction[] Instructions = {
        new VMInstruction("NOP", 0, 0, 0, 0),
        new VMInstruction("OPLOR", 1, 1, 1, 0),
        new VMInstruction("OPLAND", 1, 1, 1, 0),
        new VMInstruction("OPOR", 1, 1, 1, 0),
        new VMInstruction("OPEOR", 1, 1, 1, 0),
        new VMInstruction("OPAND", 1, 1, 1, 0),
        new VMInstruction("OPEQ", 2, 1, 1, 0),
        new VMInstruction("OPNE", 2, 1, 1, 0),
        new VMInstruction("OPGTU", 2, 1, 1, 0),
        new VMInstruction("OPLSU", 2, 1, 1, 0),
        new VMInstruction("OPGT", 2, 1, 1, 0),
        new VMInstruction("OPLS", 2, 1, 1, 0),
        new VMInstruction("OPGTEU", 2, 1, 1, 0),
        new VMInstruction("OPLSEU", 2, 1, 1, 0),
        new VMInstruction("OPGTE", 2, 1, 1, 0),
        new VMInstruction("OPLSE", 2, 1, 1, 0),
        new VMInstruction("OPBON", 1, 1, 1, 0),
        new VMInstruction("OPBOFF", 1, 1, 1, 0),
        new VMInstruction("OPSLL", 1, 1, 1, 0),
        new VMInstruction("OPSRL", 1, 1, 1, 0),
        new VMInstruction("OPADD", 2, 2, 1, 0),
        new VMInstruction("OPSUB", 2, 2, 1, 0),
        new VMInstruction("OPMUL", 2, 2, 1, 0),
        new VMInstruction("OPDIV", 2, 2, 1, 0),
        new VMInstruction("OPMOD", 2, 2, 1, 0),
        new VMInstruction("OPNOT", 1, 1, 1, 0),
        new VMInstruction("OPUMINUS", 0, 0, 1, 0),
        new VMInstruction("OPFIXADRS", 0, 0, 1, 0),
        new VMInstruction("OPBNOT", 1, 1, 1, 0),
        new VMInstruction("LABEL", 0, 0, 0, 7),
        new VMInstruction("TAG", 0, 0, 0, 6),
        new VMInstruction("PUSHV", 0, 0, 3, 3),
        new VMInstruction("POPV", 0, 0, 3, 3),
        new VMInstruction("POPVL", 0, 0, 3, 3),
        new VMInstruction("PUSHAR", 0, 0, 3, 3),
        new VMInstruction("POPAR", 0, 0, 3, 3),
        new VMInstruction("POPARL", 0, 0, 3, 3),
        new VMInstruction("POPA", 0, 0, 1, 0),
        new VMInstruction("PUSHA", 0, 0, 1, 0),
        new VMInstruction("PUSHARP", 0, 0, 3, 3),
        new VMInstruction("PUSHX", 0, 0, 1, 0),
        new VMInstruction("PUSHY", 0, 0, 1, 0),
        new VMInstruction("POPX", 0, 0, 1, 0),
        new VMInstruction("REPUSH", 0, 0, 1, 0),
        new VMInstruction("POPY", 0, 0, 1, 0),
        new VMInstruction("PUSHI", 0, 0, 3, 2),
        new VMInstruction("PUSHII", 0, 0, 3, 1),
        new VMInstruction("PUSHF", 0, 0, 3, 5),
        new VMInstruction("JMP", 0, 0, 3, 7),
        new VMInstruction("CJMP", 0, 0, 3, 7),
        new VMInstruction("NCJMP", 0, 0, 3, 7),
        new VMInstruction("JSR", 0, 0, 3, 8),
        new VMInstruction("RTS", 0, 0, 1, 0),
        new VMInstruction("CALL", 0, 0, 3, 4),
        new VMInstruction("REQ", 0, 0, 1, 0),
        new VMInstruction("REQSW", 0, 0, 1, 0),
        new VMInstruction("REQEW", 0, 0, 1, 0),
        new VMInstruction("PREQ", 0, 0, 1, 0),
        new VMInstruction("PREQSW", 0, 0, 1, 0),
        new VMInstruction("PREQEW", 0, 0, 1, 0),
        new VMInstruction("RET", 0, 0, 1, 0),
        new VMInstruction("RETN", 0, 0, 1, 0),
        new VMInstruction("RETT", 0, 0, 1, 0),
        new VMInstruction("RETTN", 0, 0, 1, 0),
        new VMInstruction("HALT", 0, 0, 1, 0),
        new VMInstruction("PUSHN", 0, 0, 3, 8),
        new VMInstruction("PUSHT", 0, 0, 3, 6),
        new VMInstruction("PUSHVP", 0, 0, 3, 3),
        new VMInstruction("PUSHFIX", 0, 0, 3, 2),
        new VMInstruction("FREQ", 0, 0, 1, 0),
        new VMInstruction("TREQ", 0, 0, 1, 0),
        new VMInstruction("BREQ", 0, 0, 1, 0),
        new VMInstruction("BFREQ", 0, 0, 1, 0),
        new VMInstruction("BTREQ", 0, 0, 1, 0),
        new VMInstruction("FREQSW", 0, 0, 1, 0),
        new VMInstruction("TREQSW", 0, 0, 1, 0),
        new VMInstruction("BREQSW", 0, 0, 1, 0),
        new VMInstruction("BFREQSW", 0, 0, 1, 0),
        new VMInstruction("BTREQSW", 0, 0, 1, 0),
        new VMInstruction("FREQEW", 0, 0, 1, 0),
        new VMInstruction("TREQEW", 0, 0, 1, 0),
        new VMInstruction("BREQEW", 0, 0, 1, 0),
        new VMInstruction("BFREQEW", 0, 0, 1, 0),
        new VMInstruction("BTREQEW", 0, 0, 1, 0),
        new VMInstruction("DRET", 0, 0, 1, 0),
        new VMInstruction("POPXJMP", 0, 0, 3, 7),
        new VMInstruction("POPXCJMP", 0, 0, 3, 7),
        new VMInstruction("POPXNCJMP", 0, 0, 3, 7),
        new VMInstruction("CALLPOPA", 0, 0, 3, 4),
        new VMInstruction("POPI0", 0, 0, 1, 0),
        new VMInstruction("POPI1", 0, 0, 1, 0),
        new VMInstruction("POPI2", 0, 0, 1, 0),
        new VMInstruction("POPI3", 0, 0, 1, 0),
        new VMInstruction("POPF0", 0, 0, 1, 0),
        new VMInstruction("POPF1", 0, 0, 1, 0),
        new VMInstruction("POPF2", 0, 0, 1, 0),
        new VMInstruction("POPF3", 0, 0, 1, 0),
        new VMInstruction("POPF4", 0, 0, 1, 0),
        new VMInstruction("POPF5", 0, 0, 1, 0),
        new VMInstruction("POPF6", 0, 0, 1, 0),
        new VMInstruction("POPF7", 0, 0, 1, 0),
        new VMInstruction("POPF8", 0, 0, 1, 0),
        new VMInstruction("POPF9", 0, 0, 1, 0),
        new VMInstruction("PUSHI0", 0, 0, 1, 0),
        new VMInstruction("PUSHI1", 0, 0, 1, 0),
        new VMInstruction("PUSHI2", 0, 0, 1, 0),
        new VMInstruction("PUSHI3", 0, 0, 1, 0),
        new VMInstruction("PUSHF0", 0, 0, 1, 0),
        new VMInstruction("PUSHF1", 0, 0, 1, 0),
        new VMInstruction("PUSHF2", 0, 0, 1, 0),
        new VMInstruction("PUSHF3", 0, 0, 1, 0),
        new VMInstruction("PUSHF4", 0, 0, 1, 0),
        new VMInstruction("PUSHF5", 0, 0, 1, 0),
        new VMInstruction("PUSHF6", 0, 0, 1, 0),
        new VMInstruction("PUSHF7", 0, 0, 1, 0),
        new VMInstruction("PUSHF8", 0, 0, 1, 0),
        new VMInstruction("PUSHF9", 0, 0, 1, 0),
        new VMInstruction("PUSHAINTER", 0, 0, 3, 1),
        new VMInstruction("SYSTEM", 0, 0, 3, 1),
        new VMInstruction("REQWAIT", 0, 0, 1, 0),
        new VMInstruction("PREQWAIT", 0, 0, 1, 0),
        new VMInstruction("REQCHG", 0, 0, 1, 0),
        new VMInstruction("ACTREQ", 0, 0, 1, 0),
    };
}
