namespace Fahrenheit.CoreLib.FFX;

/* [fkelava 7/5/23 13:14]
 * Located in the executable at +852E00h.
 *
 * This discovery was originally made by ffgriever (https://gitlab.com/ffgriever). These definitions are taken from his code wholesale.
 *
 * Without his help and patient explanations, I would not have even the slightest understanding of FFX/X-2 scripting.
 */

public sealed record FhXVMInstruction(string Name, uint OperandType, uint OperandCount, ushort InsnSize, ushort __UNKNOWN1);

public static partial class FhXVM
{
    public static readonly FhXVMInstruction[] Instructions =
    {
        new FhXVMInstruction("NOP", 0, 0, 0, 0),
        new FhXVMInstruction("OPLOR", 1, 1, 1, 0),
        new FhXVMInstruction("OPLAND", 1, 1, 1, 0),
        new FhXVMInstruction("OPOR", 1, 1, 1, 0),
        new FhXVMInstruction("OPEOR", 1, 1, 1, 0),
        new FhXVMInstruction("OPAND", 1, 1, 1, 0),
        new FhXVMInstruction("OPEQ", 2, 1, 1, 0),
        new FhXVMInstruction("OPNE", 2, 1, 1, 0),
        new FhXVMInstruction("OPGTU", 2, 1, 1, 0),
        new FhXVMInstruction("OPLSU", 2, 1, 1, 0),
        new FhXVMInstruction("OPGT", 2, 1, 1, 0),
        new FhXVMInstruction("OPLS", 2, 1, 1, 0),
        new FhXVMInstruction("OPGTEU", 2, 1, 1, 0),
        new FhXVMInstruction("OPLSEU", 2, 1, 1, 0),
        new FhXVMInstruction("OPGTE", 2, 1, 1, 0),
        new FhXVMInstruction("OPLSE", 2, 1, 1, 0),
        new FhXVMInstruction("OPBON", 1, 1, 1, 0),
        new FhXVMInstruction("OPBOFF", 1, 1, 1, 0),
        new FhXVMInstruction("OPSLL", 1, 1, 1, 0),
        new FhXVMInstruction("OPSRL", 1, 1, 1, 0),
        new FhXVMInstruction("OPADD", 2, 2, 1, 0),
        new FhXVMInstruction("OPSUB", 2, 2, 1, 0),
        new FhXVMInstruction("OPMUL", 2, 2, 1, 0),
        new FhXVMInstruction("OPDIV", 2, 2, 1, 0),
        new FhXVMInstruction("OPMOD", 2, 2, 1, 0),
        new FhXVMInstruction("OPNOT", 1, 1, 1, 0),
        new FhXVMInstruction("OPUMINUS", 0, 0, 1, 0),
        new FhXVMInstruction("OPFIXADRS", 0, 0, 1, 0),
        new FhXVMInstruction("OPBNOT", 1, 1, 1, 0),
        new FhXVMInstruction("LABEL", 0, 0, 0, 7),
        new FhXVMInstruction("TAG", 0, 0, 0, 6),
        new FhXVMInstruction("PUSHV", 0, 0, 3, 3),
        new FhXVMInstruction("POPV", 0, 0, 3, 3),
        new FhXVMInstruction("POPVL", 0, 0, 3, 3),
        new FhXVMInstruction("PUSHAR", 0, 0, 3, 3),
        new FhXVMInstruction("POPAR", 0, 0, 3, 3),
        new FhXVMInstruction("POPARL", 0, 0, 3, 3),
        new FhXVMInstruction("POPA", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHA", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHARP", 0, 0, 3, 3),
        new FhXVMInstruction("PUSHX", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHY", 0, 0, 1, 0),
        new FhXVMInstruction("POPX", 0, 0, 1, 0),
        new FhXVMInstruction("REPUSH", 0, 0, 1, 0),
        new FhXVMInstruction("POPY", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHI", 0, 0, 3, 2),
        new FhXVMInstruction("PUSHII", 0, 0, 3, 1),
        new FhXVMInstruction("PUSHF", 0, 0, 3, 5),
        new FhXVMInstruction("JMP", 0, 0, 3, 7),
        new FhXVMInstruction("CJMP", 0, 0, 3, 7),
        new FhXVMInstruction("NCJMP", 0, 0, 3, 7),
        new FhXVMInstruction("JSR", 0, 0, 3, 8),
        new FhXVMInstruction("RTS", 0, 0, 1, 0),
        new FhXVMInstruction("CALL", 0, 0, 3, 4),
        new FhXVMInstruction("REQ", 0, 0, 1, 0),
        new FhXVMInstruction("REQSW", 0, 0, 1, 0),
        new FhXVMInstruction("REQEW", 0, 0, 1, 0),
        new FhXVMInstruction("PREQ", 0, 0, 1, 0),
        new FhXVMInstruction("PREQSW", 0, 0, 1, 0),
        new FhXVMInstruction("PREQEW", 0, 0, 1, 0),
        new FhXVMInstruction("RET", 0, 0, 1, 0),
        new FhXVMInstruction("RETN", 0, 0, 1, 0),
        new FhXVMInstruction("RETT", 0, 0, 1, 0),
        new FhXVMInstruction("RETTN", 0, 0, 1, 0),
        new FhXVMInstruction("HALT", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHN", 0, 0, 3, 8),
        new FhXVMInstruction("PUSHT", 0, 0, 3, 6),
        new FhXVMInstruction("PUSHVP", 0, 0, 3, 3),
        new FhXVMInstruction("PUSHFIX", 0, 0, 3, 2),
        new FhXVMInstruction("FREQ", 0, 0, 1, 0),
        new FhXVMInstruction("TREQ", 0, 0, 1, 0),
        new FhXVMInstruction("BREQ", 0, 0, 1, 0),
        new FhXVMInstruction("BFREQ", 0, 0, 1, 0),
        new FhXVMInstruction("BTREQ", 0, 0, 1, 0),
        new FhXVMInstruction("FREQSW", 0, 0, 1, 0),
        new FhXVMInstruction("TREQSW", 0, 0, 1, 0),
        new FhXVMInstruction("BREQSW", 0, 0, 1, 0),
        new FhXVMInstruction("BFREQSW", 0, 0, 1, 0),
        new FhXVMInstruction("BTREQSW", 0, 0, 1, 0),
        new FhXVMInstruction("FREQEW", 0, 0, 1, 0),
        new FhXVMInstruction("TREQEW", 0, 0, 1, 0),
        new FhXVMInstruction("BREQEW", 0, 0, 1, 0),
        new FhXVMInstruction("BFREQEW", 0, 0, 1, 0),
        new FhXVMInstruction("BTREQEW", 0, 0, 1, 0),
        new FhXVMInstruction("DRET", 0, 0, 1, 0),
        new FhXVMInstruction("POPXJMP", 0, 0, 3, 7),
        new FhXVMInstruction("POPXCJMP", 0, 0, 3, 7),
        new FhXVMInstruction("POPXNCJMP", 0, 0, 3, 7),
        new FhXVMInstruction("CALLPOPA", 0, 0, 3, 4),
        new FhXVMInstruction("POPI0", 0, 0, 1, 0),
        new FhXVMInstruction("POPI1", 0, 0, 1, 0),
        new FhXVMInstruction("POPI2", 0, 0, 1, 0),
        new FhXVMInstruction("POPI3", 0, 0, 1, 0),
        new FhXVMInstruction("POPF0", 0, 0, 1, 0),
        new FhXVMInstruction("POPF1", 0, 0, 1, 0),
        new FhXVMInstruction("POPF2", 0, 0, 1, 0),
        new FhXVMInstruction("POPF3", 0, 0, 1, 0),
        new FhXVMInstruction("POPF4", 0, 0, 1, 0),
        new FhXVMInstruction("POPF5", 0, 0, 1, 0),
        new FhXVMInstruction("POPF6", 0, 0, 1, 0),
        new FhXVMInstruction("POPF7", 0, 0, 1, 0),
        new FhXVMInstruction("POPF8", 0, 0, 1, 0),
        new FhXVMInstruction("POPF9", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHI0", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHI1", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHI2", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHI3", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHF0", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHF1", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHF2", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHF3", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHF4", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHF5", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHF6", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHF7", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHF8", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHF9", 0, 0, 1, 0),
        new FhXVMInstruction("PUSHAINTER", 0, 0, 3, 1),
        new FhXVMInstruction("SYSTEM", 0, 0, 3, 1),
        new FhXVMInstruction("REQWAIT", 0, 0, 1, 0),
        new FhXVMInstruction("PREQWAIT", 0, 0, 1, 0),
        new FhXVMInstruction("REQCHG", 0, 0, 1, 0),
        new FhXVMInstruction("ACTREQ", 0, 0, 1, 0),
    };
}
