<Project Sdk="Microsoft.NET.Sdk">

    <!-- ASSEMBLY BASIC PROPERTIES -->
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <!-- ASSEMBLY ADDITIONAL PROPERTIES -->
    <PropertyGroup>
        <AssemblyName>fhmodmgr</AssemblyName>
        <AssemblyTitle>Fahrenheit Mod Manager</AssemblyTitle>
        <Product>Fahrenheit Mod Manager</Product>
    </PropertyGroup>

    <!-- PUBLISH SETTINGS -->
    <PropertyGroup>
        <SelfContained>false</SelfContained>
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    </PropertyGroup>

    <!-- APPLICATION ASSETS -->
    <PropertyGroup>
        <ApplicationIcon>..\..\assets\fh_base_256.ico</ApplicationIcon>
    </PropertyGroup>

    <!-- SHARED FILE LINKS -->
    <ItemGroup>
        <None Include="$(SolutionDir).editorconfig" Link=".editorconfig" />
    </ItemGroup>

    <!-- PROJECT REFERENCES -->
    <ItemGroup>
        <ProjectReference Include="..\core\Fahrenheit.csproj" />
    </ItemGroup>

    <!-- EXTERNAL PROJECT REFS -->
    <ItemGroup>
        <PackageReference Include="Hexa.NET.ImGui.Backends" Version="3.1.0-experimental" />
        <PackageReference Include="Hexa.NET.ImGui.Backends.SDL3" Version="3.1.0-experimental" />
        <PackageReference Include="Hexa.NET.SDL3" Version="1.2.11" />
        <PackageReference Include="Hexa.NET.OpenGL3" Version="1.1.0" />
        <PackageReference Include="NativeFileDialogCore" Version="1.0.3" />
    </ItemGroup>

    <!-- FONT ASSETS -->
    <ItemGroup>
        <Content Include="..\..\assets\NotoSans-VariableFont_wdth,wght.ttf">
            <Link>resources\fonts\NotoSans-VariableFont_wdth,wght.ttf</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </Content>
    </ItemGroup>

</Project>
