/* [fkelava 9/5/23 23:37]
 * source: MS Store ver.
 * header: __BATTLE_ATEL__
 *
 * /ffx_ps2/ffx/proj2/chr/ath/battle/btlhead.src
 * 
 * Partial. Many constants yet to come along with other stuff.
 */

namespace Fahrenheit.CoreLib;

public enum FhXChrStatId : T_XChrStatId
{
    STAT_HP                        = 0,   // ＨＰ
    STAT_MP                        = 1,   // ＭＰ
    STAT_MAXHP                     = 2,   // 最大ＨＰ
    STAT_MAXMP                     = 3,   // 最大ＭＰ
    STAT_ALIVE                     = 4,   // 生死
    STAT_POISON                    = 5,   // 毒
    STAT_STONE                     = 6,   // 石化
    STAT_ZOMBIE                    = 7,   // ゾンビ
    STAT_WEAK                      = 8,   // 弱り
    STAT_STR                       = 9,   // 力
    STAT_VIT                       = 10,  // 体力
    STAT_MAG                       = 11,  // 魔力
    STAT_SPIRIT                    = 12,  // 精神
    STAT_DEX                       = 13,  // すばやさ
    STAT_LUCK                      = 14,  // 運
    STAT_AVOID                     = 15,  // 回避率
    STAT_HIT                       = 16,  // 命中率
    STAT_POISON_PER                = 17,  // 毒ダメージ割合
    STAT_LIMIT_TYPE                = 18,  // リミットタイプ
    STAT_LIMIT_GAUGE               = 19,  // リミットゲージ
    STAT_LIMIT_GAUGE_MAX           = 20,  // リミットゲージ最大
    STAT_INBATTLE                  = 21,  // バトルにいるかどうか
    STAT_MAN                       = 22,  // 男フラグ
    STAT_FEMALE                    = 23,  // 女フラグ
    STAT_SUMMON                    = 24,  // 召喚獣フラグ
    STAT_MONSTER                   = 25,  // モンスターフラグ
    STAT_FLY                       = 26,  // 飛んでるフラグ
    STAT_WILL_DIE                  = 27,  // 死ぬかもフラグ
    STAT_AREA                      = 28,  // 立ち位置エリア
    STAT_POS                       = 29,  // 立ち位置番号
    STAT_FAR                       = 30,  // 遠近設定
    STAT_GROUP                     = 31,  // グループ設定
    STAT_SP_HARD                   = 32,  // 硬さビット
    STAT_SP_RATIO                  = 33,  // 割合ダメージフラグ
    STAT_SP_ZOMBIE                 = 34,  // ゾンビ一撃死フラグ
    STAT_SP_SEE                    = 35,  // 見破るフラグ
    STAT_SP_LIVE                   = 36,  // ライブラフラグ
    STAT_POWER_BREAK               = 37,  // パワーブレイク
    STAT_MAGIC_BREAK               = 38,  // マジックブレイク
    STAT_ARMOR_BREAK               = 39,  // アーマーブレイク
    STAT_MENTAL_BREAK              = 40,  // メンタルブレイク
    STAT_CONFUSE                   = 41,  // こんらん
    STAT_BERSERK                   = 42,  // バーサク
    STAT_PROV                      = 43,  // 挑発
    STAT_THREAT                    = 44,  // 威嚇
    STAT_SLEEP                     = 45,  // 睡眠
    STAT_SILENCE                   = 46,  // 沈黙
    STAT_DARK                      = 47,  // 暗闇
    STAT_SHELL                     = 48,  // シェル
    STAT_PROTESS                   = 49,  // プロテス
    STAT_REFLECT                   = 50,  // リフレク
    STAT_BAWATER                   = 51,  // バウォタ
    STAT_BAFIRE                    = 52,  // バファイ
    STAT_BATHUNDER                 = 53,  // バサンダ
    STAT_BACOLD                    = 54,  // バコルド
    STAT_REGEN                     = 55,  // リジェネ
    STAT_HASTE                     = 56,  // へースト
    STAT_SLOW                      = 57,  // スロウ
    ABILITY_SEE                    = 58,  // みやぶる
    ABILITY_LEAD                   = 59,  // さきがけ
    ABILITY_FIRST                  = 60,  // せんせい
    ABILITY_COUNTER                = 61,  // カウンター
    ABILITY_COUNTER2               = 62,  // カウンター２
    ABILITY_DARK                   = 63,  // 暗黒剣
    ABILITY_AP2                    = 64,  // ＡＰ２倍
    ABILITY_EXP2                   = 65,  // ＥＸＰ２倍
    ABILITY_BOOSTER                = 66,  // ブースター
    ABILITY_MAGIC_COUNTER          = 67,  // 魔法カウンター
    ABILITY_MEDICINE               = 68,  // くすりのちしき
    ABILITY_AUTO_POTION            = 69,  // オートポーション
    ABILITY_AUTO_CUREALL           = 70,  // オート万能薬
    ABILITY_AUTO_PHENIX            = 71,  // オートフェニックス
    ABILITY_LIMITUP                = 72,  // リミットアップ
    ABILITY_DREAM                  = 73,  // 夢オチ
    ABILITY_PIERCE                 = 74,  // かんつう
    ABILITY_EXCHANGE               = 75,  // 自動交代
    ABILITY_HP_RECOVER             = 76,  // 歩くとＨＰ回復
    ABILITY_MP_RECOVER             = 77,  // 歩くとＭＰ回復
    ABILITY_NONENCOUNT             = 78,  // エンカウントなし
    STAT_DEATH_PATTERN             = 79,  // 死にパターン
    STAT_EVENT_CHR                 = 80,  // イベントキャラクターフラグ
    STAT_ACTION                    = 81,  // 行動フラグ
    STAT_CURSOR                    = 82,  // カーソルフラグ
    STAT_CTB_LIST                  = 83,  // CTB リストフラグ
    STAT_VISIBLE                   = 84,  // 表示フラグ
    STAT_MOVE_AREA                 = 85,  // 移動エリア
    STAT_MOVE_POS                  = 86,  // 移動位置
    STAT_EFFLV                     = 87,  // エフェクトレベル
    STAT_MODEL                     = 88,  // モデルフラグ
    STAT_DAMAGE_CHR                = 89,  // ダメージを受けるキャラクター
    STAT_MOVE_TARGET               = 90,  // 移動ターゲットキャラクター
    STAT_MOTIONLV                  = 91,  // モーションレベル
    STAT_NOP                       = 92,  // なし
    STAT_MOVE_FLAG                 = 93,  // 移動フラグ
    STAT_LIVE_MOTION               = 94,  // 行き返りモーション
    STAT_ADJUST_POS                = 95,  // 微調整位置フラグ
    STAT_HEIGHT_ON                 = 96,  // 高さオンフラグ
    STAT_SLEEP_RECOVER_FLAG        = 97,  // 眠りからの復活フラグ
    STAT_ABS_FIRE                  = 98,  // 吸収属性 炎
    STAT_ABS_COLD                  = 99,  // 吸収属性 冷気
    STAT_ABS_THUNDER               = 100, // 吸収属性 雷
    STAT_ABS_WATER                 = 101, // 吸収属性 水
    STAT_ABS_HOLY                  = 102, // 吸収属性 聖
    STAT_INV_FIRE                  = 103, // 無効属性 炎
    STAT_INV_COLD                  = 104, // 無効属性 冷気
    STAT_INV_THUNDER               = 105, // 無効属性 雷
    STAT_INV_WATER                 = 106, // 無効属性 水
    STAT_INV_HOLY                  = 107, // 無効属性 聖
    STAT_HALF_FIRE                 = 108, // 半減属性 炎
    STAT_HALF_COLD                 = 109, // 半減属性 冷気
    STAT_HALF_THUNDER              = 110, // 半減属性 雷
    STAT_HALF_WATER                = 111, // 半減属性 水
    STAT_HALF_HOLY                 = 112, // 半減属性 聖
    STAT_WEAK_FIRE                 = 113, // 弱点属性 炎
    STAT_WEAK_COLD                 = 114, // 弱点属性 冷気
    STAT_WEAK_THUNDER              = 115, // 弱点属性 雷
    STAT_WEAK_WATER                = 116, // 弱点属性 水
    STAT_WEAK_HOLY                 = 117, // 弱点属性 聖
    STAT_ADJUST_POS_FLAG           = 118, // 位置調整フラグ
    STAT_INV_PHYSIC_MOTION         = 119, // 物理無効モーションフラグ
    STAT_INV_MAGIC_MOTION          = 120, // 魔法無効モーションフラグ
    STAT_STEAL_COUNT               = 121, // 盗まれカウント
    STAT_WAIT_MOTION_FLAG          = 122, // 待機モーションフラグ
    STAT_ATTACK_RETURN_FLAG        = 123, // 攻撃帰りフラグ
    STAT_ATTACK_NORMAL_FRAME       = 124, // 攻撃フレーム数：通常
    STAT_DISABLE_MOVE_FLAG         = 125, // 移動不可フラグ
    STAT_DISABLE_JUMP_FLAG         = 126, // ジャンプ不可フラグ
    STAT_BODYHIT_FLAG              = 127, // 体の当たり判定
    STAT_EFFVAR                    = 128, // エフェクト変数
    STAT_ITEM                      = 129, // 盗めるアイテム
    STAT_ITEM_NUM                  = 130, // 盗めるアイテム数
    STAT_RAREITEM                  = 131, // 盗めるレアアイテム
    STAT_RAREITEM_NUM              = 132, // 盗めるレアアイテム数
    STAT_MAGICLV                   = 133, // 魔法レベル
    STAT_APPEAR_MOTION_FLAG        = 134, // 出現フラグ
    STAT_CURSOR_ELEMENT            = 135, // カーソルエレメント
    STAT_LIMIT_BAR_FLAG_CAM        = 136, // リミットバーフラグ：カメラ用
    STAT_LIMIT_BAR_FLAG            = 137, // リミットバーフラグ
    STAT_DROP1                     = 138, // 通常アイテム１落とす確率
    STAT_DROP2                     = 139, // 通常アイテム２落とす確率
    STAT_WEAPON_DROP               = 140, // 武器落とす確率
    STAT_STEAL                     = 141, // 盗む確率
    STAT_EXIST_FLAG                = 142, // 存在フラグ
    STAT_LIVE                      = 143, // ライブラ
    STAT_STR_MEMORY                = 144, // 力の記憶
    STAT_MAG_MEMORY                = 145, // 魔力の記憶
    STAT_DEX_MEMORY                = 146, // すばやさの記憶
    STAT_MOVE_MEMORY               = 147, // 移動の記憶
    STAT_ABILITY_MEMORY            = 148, // アビリティーの記憶
    STAT_DODGE                     = 149, // よける
    STAT_DEFEND                    = 150, // まもる
    STAT_BLOW                      = 151, // 吹き飛ばし
    STAT_RELIFE                    = 152, // リレイズ
    STAT_CURSE                     = 153, // カーズ
    STAT_DEFENSE                   = 154, // ぼうぎょ
    STAT_PROTECT                   = 155, // かばう
    STAT_IRON                      = 156, // てっぺき
    STAT_DEATH_SENTENCE            = 157, // 死の宣告
    STAT_MOTION_TYPE               = 158, // モーションタイプ
    STAT_DEATH_SENTENCE_START      = 159, // 死の宣告：初期値
    STAT_DEATH_SENTENCE_COUNT      = 160, // 死の宣告：カウント
    STAT_DMG_DIR                   = 161, // ダメージ方向
    STAT_DIRECTION_CHANGE_FLAG     = 162, // 方向チェックフラグ
    STAT_DIRECTION_CHANGE_EFFECT   = 163, // 方向変更有効フラグ
    STAT_DIRECTION_FIX_FLAG        = 164, // 方向固定フラグ
    STAT_HIT_TERMINATE_FLAG        = 165, // ヒット終了フラグ
    STAT_DAMAGE_HP                 = 166, // ＨＰダメージ
    STAT_DAMAGE_MP                 = 167, // ＭＰダメージ
    STAT_DAMAGE_CTB                = 168, // ＣＴＢダメージ
    STAT_APPEAR_INVISIBLE_FLAG     = 169, // 出現時見えないフラグ
    STAT_EFFECT_HIT_NUM            = 170, // ヒットエフェクト番号
    STAT_AVOID_FLAG                = 171, // 避けフラグ
    STAT_BLOW_EXIST_FLAG           = 172, // 吹き飛ばし存在フラグ
    STAT_ESCAPE_FLAG               = 173, // 逃げるフラグ
    STAT_HIDE                      = 174, // ハイド
    STAT_DEF_DEATH                 = 175, // 防御：戦闘可能
    STAT_DEF_ZOMBIE                = 176, // 防御：ゾンビ
    STAT_DEF_STONE                 = 177, // 防御：石化
    STAT_DEF_POISON                = 178, // 防御：毒
    STAT_DEF_POWER_BREAK           = 179, // 防御：パワーブレイク
    STAT_DEF_MAGIC_BREAK           = 180, // 防御：マジックブレイク
    STAT_DEF_ARMOR_BREAK           = 181, // 防御：アーマーブレイク
    STAT_DEF_MENTAL_BREAK          = 182, // 防御：メンタルブレイク
    STAT_DEF_CONFUSE               = 183, // 防御：こんらん
    STAT_DEF_BERSERK               = 184, // 防御：バーサク
    STAT_DEF_PROV                  = 185, // 防御：挑発
    STAT_DEF_THREAT                = 186, // 防御：威嚇
    STAT_DEF_SLEEP                 = 187, // 防御：睡眠
    STAT_DEF_SILENCE               = 188, // 防御：沈黙
    STAT_DEF_DARK                  = 189, // 防御：暗闇
    STAT_DEF_SHELL                 = 190, // 防御：シェル
    STAT_DEF_PROTESS               = 191, // 防御：プロテス
    STAT_DEF_REFLECT               = 192, // 防御：リフレク
    STAT_DEF_BAWATER               = 193, // 防御：バウォタ
    STAT_DEF_BAFIRE                = 194, // 防御：バファイ
    STAT_DEF_BATHUNDER             = 195, // 防御：バサンダ
    STAT_DEF_BACOLD                = 196, // 防御：バコルド
    STAT_DEF_REGEN                 = 197, // 防御：リジェネ
    STAT_DEF_HASTE                 = 198, // 防御：へースト
    STAT_DEF_SLOW                  = 199, // 防御：スロウ
    STAT_DEF_LIVE                  = 200, // 防御：ライブラ
    STAT_DEF_STR_MEMORY            = 201, // 防御：力の記憶
    STAT_DEF_MAG_MEMORY            = 202, // 防御：魔力の記憶
    STAT_DEF_DEX_MEMORY            = 203, // 防御：すばやさの記憶
    STAT_DEF_MOVE_MEMORY           = 204, // 防御：移動の記憶
    STAT_DEF_ABILITY_MEMORY        = 205, // 防御：アビリティーの記憶
    STAT_DEF_DODGE                 = 206, // 防御：よける
    STAT_DEF_DEFEND                = 207, // 防御：まもる
    STAT_DEF_RELIFE                = 208, // 防御：リレイズ
    STAT_DEF_BLOW                  = 209, // 防御：吹き飛ばし
    STAT_DEF_CURSE                 = 210, // 防御：カーズ
    STAT_DEF_DEFENSE               = 211, // 防御：ぼうぎょ
    STAT_DEF_PROTECT               = 212, // 防御：かばう
    STAT_DEF_IRON                  = 213, // 防御：てっぺき
    STAT_DEF_DEATH_SENTENCE        = 214, // 防御：死の宣告
    STAT_HP_LIST                   = 215, // ＨＰリスト表示
    STAT_VISIBLE_CAM               = 216, // カメラ用表示フラグ
    STAT_VISIBLE_OUT               = 217, // バトル終了時の表示フラグ
    STAT_ROUND                     = 218, // 指定方向フレーム
    STAT_ROUND_RETURN              = 219, // 基本方向フレーム
    STAT_WIN_POSE                  = 220, // 勝利のポーズ
    STAT_VIGOR                     = 221, // 元気状態
    STAT_FAST_MODEL_FLAG           = 222, // 速いモデルフラグ
    STAT_ALIVE_NOT_STONE           = 223, // 生きていて石化でないとき
    STAT_COMMAND_TYPE              = 224, // コマンドタイプ
    STAT_EFFECT_TARGET_FLAG        = 225, // エフェクトターゲットフラグ
    STAT_MAGIC_EFFECT_GROUND       = 226, // 地上：魔法エフェクト番号
    STAT_MAGIC_EFFECT_WATER        = 227, // 水中：魔法エフェクト番号
    STAT_IDLE2_PROB                = 228, // idle2 の確率
    STAT_ATTACK_MOTION_TYPE        = 229, // 攻撃モーションタイプ
    STAT_ATTACK_INC_SPEED          = 230, // 攻撃：加速％
    STAT_ATTACK_DEC_SPEED          = 231, // 攻撃：減速％
    STAT_CTB                       = 232, // ＣＴＢ値
    STAT_APPEAR_COUNT              = 233, // 出現カウント
    STAT_MOTION_NUM                = 234, // モーション補間番号
    STAT_INFO_MES_ID               = 235, // 情報：メッセージＩＤ
    STAT_LIVE_MES_ID               = 236, // ライブラ：メッセージＩＤ
    STAT_VISIBLE_EFF               = 237, // エフェクト用表示フラグ
    STAT_MOTION_DISPOSE_FLAG       = 238, // モーション解放フラグ
    STAT_MODEL_DISPOSE_FLAG        = 239, // モデル解放フラグ
    STAT_DEF_CTB                   = 240, // CTB 防御
    STAT_SHADOW                    = 241, // 影
    STAT_DEATH                     = 242, // 死亡
    STAT_DEATH_STONE               = 243, // 死亡か石化
    STAT_CHECK_POS                 = 244, // 立ち位置から外れているかチェック
    STAT_WIN_SE                    = 245, // 勝利のＳＥ
    STAT_ATTACK_NUM                = 246, // 攻撃回数
    STAT_NEAR_MOTION               = 247, // 近距離モーション
    STAT_TALK_STAT1                = 248, // 喋れる状態１
    STAT_TALK_STAT2                = 249, // 喋れる状態２
    STAT_NEAR_MOTION_SET           = 250, // 近距離攻撃強制設定
    STAT_MOTION_SPEED_NORMAL       = 251, // 通常モーションスピード
    STAT_MOTION_SPEED_NORMAL_START = 252, // 通常モーションスピード：モーション開始時
    STAT_OWN_ATTACK_NEAR           = 253, // 自分攻撃近距離フラグ
    STAT_TALK_STAT3                = 254, // 喋れる状態３
    STAT_COMMAND_SET               = 255, // コマンド設定可能状態
    STAT_PROV_COMMAND_FLAG         = 256, // 挑発を自分で判断するフラグ
    STAT_PROV_CHR                  = 257, // 挑発された相手
    STAT_USE_MP0                   = 258, // 使用ＭＰ０
    STAT_ICON_NUMBER               = 259, // アイコン番号
    STAT_SOUND_HIT_NUM             = 260, // ヒットＳＥ番号
    STAT_DAMAGE_NUM_POS            = 261, // ダメージ数値位置
    STAT_SUMMONER                  = 262, // 召喚者番号
    STAT_SP_INVINCIBLE             = 263, // 無敵
    STAT_SP_INV_MAGIC              = 264, // 魔法無効
    STAT_SP_INV_PHYSIC             = 265, // 物理無効
    STAT_BLUE_MAGIC                = 266, // 青魔法
    STAT_SP_DISABLE_ZAN            = 267, // 斬魔刀で切れない
    STAT_OVER_KILL_HP              = 268, // オーバーキルＨＰ
    STAT_RETURN_MOTION_TYPE        = 269, // 戻りモーションタイプ
    STAT_CAM_WIDTH                 = 270, // カメラの太さ
    STAT_CAM_HEIGHT                = 271, // カメラの高さ
    STAT_HEIGHT                    = 272, // 高さ
    STAT_YOUJINBO                  = 273, // ようじんぼうとの相性
    STAT_PAYMENT                   = 274, // ようじんぼうへの支払い額
    STAT_MONSTER_VALUE_MAX         = 275, // モンスター係数：最大
    STAT_COMMAND_EXE_COUNT         = 276, // コマンド実行回数
    STAT_CONSENT                   = 277, // 納得フラグ
    STAT_ATTACK_NEAR_FRAME         = 278, // 攻撃フレーム数：近距離
    STAT_ENERGY                    = 279, // メーガスやる気
    STAT_LIMIT_GAUGE_ADD           = 280, // リミットゲージ加算
    STAT_HP_HALF                   = 281, // ＨＰ半分以下チェック
    STAT_LIMIT_GAUGE_CHECK         = 282, // リミットゲージチェック
    STAT_HP_CHECK                  = 283, // ＨＰが満タンかチェック
    STAT_MP_CHECK                  = 284, // ＭＰが満タンかチェック
    STAT_BA_ALL_CHECK              = 285, // バ系が全てかかっているかをチェック
    STAT_SHELL_REFLECT             = 286, // シェルかリフレクがかかっている
    STAT_PROTESS_REFLECT           = 287, // プロテスかリフレクがかかっている
    STAT_HASTE_REFLECT             = 288, // ヘイストかリフレクがかかっている
    STAT_WEAK_MOTION               = 289, // 弱りモーションの取得
    STAT_SP_WAIRO                  = 290, // わいろ
    STAT_ATTACK_MOTION_FRAME       = 291, // 攻撃通常フレーム数
    STAT_MOTION_TYPE_RESET         = 292, // モーションタイプリセット
    STAT_MOTION_TYPE_ADD           = 293, // モーションタイプ追加
    STAT_DEATH_STATUS              = 294, // 死亡ステータス
    STAT_TARGET_LIST               = 295, // ターゲットリストフラグ
    STAT_LIMIT_BAR_POS             = 296, // リミットバー位置
    STAT_CENTER_CHR_FLAG           = 297, // 中央キャラフラグ
    STAT_SAME_TARGET_CHECK         = 298, // 同じターゲットチェック
    STAT_GET_AP                    = 299, // 獲得：ＡＰ値
    STAT_GET_OVER_AP               = 300, // 獲得：オーバーキルＡＰ値
    STAT_GET_GILL                  = 301, // 獲得：ギル
    STAT_STR_UP                    = 302, // 力　　　：調整値
    STAT_VIT_UP                    = 303, // 体力　　：調整値
    STAT_MAG_UP                    = 304, // 魔力　　：調整値
    STAT_SPIRIT_UP                 = 305, // 精神　　：調整値
    STAT_DEX_UP                    = 306, // すばやさ：調整値
    STAT_LUCK_UP                   = 307, // 運　　　：調整値
    STAT_AVOID_UP                  = 308, // 回避率　：調整値
    STAT_HIT_UP                    = 309, // 命中率　：調整値
    STAT_USE_MP                    = 310, // 使用ＭＰ値
    STAT_USE_LIMIT                 = 311, // 使用リミット値
    STAT_USE_LIMIT_ALL             = 312, // 使用リミット全フラグ
    STAT_CONTINUE_MAGIC            = 313, // 連続魔法使用フラグ
    STAT_ITEM1_COM                 = 314, // 落とすアイテム１：コモン
    STAT_ITEM1_RARE                = 315, // 落とすアイテム１：レア
    STAT_ITEM2_COM                 = 316, // 落とすアイテム２：コモン
    STAT_ITEM2_RARE                = 317, // 落とすアイテム２：レア
    STAT_ITEM1_COM_OVER_KILL       = 318, // 落とすアイテム１：コモン：オーバーキル用
    STAT_ITEM1_RARE_OVER_KILL      = 319, // 落とすアイテム１：レア：オーバーキル用
    STAT_ITEM2_COM_OVER_KILL       = 320, // 落とすアイテム２：コモン：オーバーキル用
    STAT_ITEM2_RARE_OVER_KILL      = 321, // 落とすアイテム２：レア：オーバーキル用
    STAT_ITEM1_COM_NUM             = 322, // 落とすアイテム１：コモン：数
    STAT_ITEM1_RARE_NUM            = 323, // 落とすアイテム１：レア：数
    STAT_ITEM2_COM_NUM             = 324, // 落とすアイテム２：コモン：数
    STAT_ITEM2_RARE_NUM            = 325, // 落とすアイテム２：レア：数
    STAT_ITEM1_COM_OVER_KILL_NUM   = 326, // 落とすアイテム１：コモン：オーバーキル用：数
    STAT_ITEM1_RARE_OVER_KILL_NUM  = 327, // 落とすアイテム１：レア：オーバーキル用：数
    STAT_ITEM2_COM_OVER_KILL_NUM   = 328, // 落とすアイテム２：コモン：オーバーキル用：数
    STAT_ITEM2_RARE_OVER_KILL_NUM  = 329, // 落とすアイテム２：レア：オーバーキル用：数
    STAT_DEATH_RETURN              = 330, // 死亡帰りフラグ
    STAT_LINEAR_MOVE_RESET         = 331, // 直線移動リセット
    STAT_BODYHIT_DIRECT            = 332, // 直接ボディヒット設定
    STAT_JOIN                      = 333, // 仲間になっている
    STAT_ETERNAL_RELIFE            = 334, // 永久リライフ
    STAT_NECK_TARGET_FLAG          = 335, // 首ターゲットなし
    STAT_VISIBLE_OUT_ON            = 336, // バトル終了時表示フラグ
    STAT_REGEN_DAMAGE_FLAG         = 337, // リジェネダメージを画面内に入れるフラグ
    STAT_NUM_PRINT_ELEMENT         = 338, // 番号表示エレメント
}