/* [fkelava 9/5/23 23:37]
 * source: MS Store ver.
 * header: __BATTLE_ATEL__
 *
 * /ffx_ps2/ffx/proj2/chr/ath/battle/btlhead.src
 * 
 * Partial. Many constants yet to come along with other stuff.
 */

namespace Fahrenheit.CoreLib;

public static class FhXChrStatId
{
    public const T_XChrStatId STAT_HP                        = 0;   // ＨＰ
    public const T_XChrStatId STAT_MP                        = 1;   // ＭＰ
    public const T_XChrStatId STAT_MAXHP                     = 2;   // 最大ＨＰ
    public const T_XChrStatId STAT_MAXMP                     = 3;   // 最大ＭＰ
    public const T_XChrStatId STAT_ALIVE                     = 4;   // 生死
    public const T_XChrStatId STAT_POISON                    = 5;   // 毒
    public const T_XChrStatId STAT_STONE                     = 6;   // 石化
    public const T_XChrStatId STAT_ZOMBIE                    = 7;   // ゾンビ
    public const T_XChrStatId STAT_WEAK                      = 8;   // 弱り
    public const T_XChrStatId STAT_STR                       = 9;   // 力
    public const T_XChrStatId STAT_VIT                       = 10;  // 体力
    public const T_XChrStatId STAT_MAG                       = 11;  // 魔力
    public const T_XChrStatId STAT_SPIRIT                    = 12;  // 精神
    public const T_XChrStatId STAT_DEX                       = 13;  // すばやさ
    public const T_XChrStatId STAT_LUCK                      = 14;  // 運
    public const T_XChrStatId STAT_AVOID                     = 15;  // 回避率
    public const T_XChrStatId STAT_HIT                       = 16;  // 命中率
    public const T_XChrStatId STAT_POISON_PER                = 17;  // 毒ダメージ割合
    public const T_XChrStatId STAT_LIMIT_TYPE                = 18;  // リミットタイプ
    public const T_XChrStatId STAT_LIMIT_GAUGE               = 19;  // リミットゲージ
    public const T_XChrStatId STAT_LIMIT_GAUGE_MAX           = 20;  // リミットゲージ最大
    public const T_XChrStatId STAT_INBATTLE                  = 21;  // バトルにいるかどうか
    public const T_XChrStatId STAT_MAN                       = 22;  // 男フラグ
    public const T_XChrStatId STAT_FEMALE                    = 23;  // 女フラグ
    public const T_XChrStatId STAT_SUMMON                    = 24;  // 召喚獣フラグ
    public const T_XChrStatId STAT_MONSTER                   = 25;  // モンスターフラグ
    public const T_XChrStatId STAT_FLY                       = 26;  // 飛んでるフラグ
    public const T_XChrStatId STAT_WILL_DIE                  = 27;  // 死ぬかもフラグ
    public const T_XChrStatId STAT_AREA                      = 28;  // 立ち位置エリア
    public const T_XChrStatId STAT_POS                       = 29;  // 立ち位置番号
    public const T_XChrStatId STAT_FAR                       = 30;  // 遠近設定
    public const T_XChrStatId STAT_GROUP                     = 31;  // グループ設定
    public const T_XChrStatId STAT_SP_HARD                   = 32;  // 硬さビット
    public const T_XChrStatId STAT_SP_RATIO                  = 33;  // 割合ダメージフラグ
    public const T_XChrStatId STAT_SP_ZOMBIE                 = 34;  // ゾンビ一撃死フラグ
    public const T_XChrStatId STAT_SP_SEE                    = 35;  // 見破るフラグ
    public const T_XChrStatId STAT_SP_LIVE                   = 36;  // ライブラフラグ
    public const T_XChrStatId STAT_POWER_BREAK               = 37;  // パワーブレイク
    public const T_XChrStatId STAT_MAGIC_BREAK               = 38;  // マジックブレイク
    public const T_XChrStatId STAT_ARMOR_BREAK               = 39;  // アーマーブレイク
    public const T_XChrStatId STAT_MENTAL_BREAK              = 40;  // メンタルブレイク
    public const T_XChrStatId STAT_CONFUSE                   = 41;  // こんらん
    public const T_XChrStatId STAT_BERSERK                   = 42;  // バーサク
    public const T_XChrStatId STAT_PROV                      = 43;  // 挑発
    public const T_XChrStatId STAT_THREAT                    = 44;  // 威嚇
    public const T_XChrStatId STAT_SLEEP                     = 45;  // 睡眠
    public const T_XChrStatId STAT_SILENCE                   = 46;  // 沈黙
    public const T_XChrStatId STAT_DARK                      = 47;  // 暗闇
    public const T_XChrStatId STAT_SHELL                     = 48;  // シェル
    public const T_XChrStatId STAT_PROTESS                   = 49;  // プロテス
    public const T_XChrStatId STAT_REFLECT                   = 50;  // リフレク
    public const T_XChrStatId STAT_BAWATER                   = 51;  // バウォタ
    public const T_XChrStatId STAT_BAFIRE                    = 52;  // バファイ
    public const T_XChrStatId STAT_BATHUNDER                 = 53;  // バサンダ
    public const T_XChrStatId STAT_BACOLD                    = 54;  // バコルド
    public const T_XChrStatId STAT_REGEN                     = 55;  // リジェネ
    public const T_XChrStatId STAT_HASTE                     = 56;  // へースト
    public const T_XChrStatId STAT_SLOW                      = 57;  // スロウ
    public const T_XChrStatId ABILITY_SEE                    = 58;  // みやぶる
    public const T_XChrStatId ABILITY_LEAD                   = 59;  // さきがけ
    public const T_XChrStatId ABILITY_FIRST                  = 60;  // せんせい
    public const T_XChrStatId ABILITY_COUNTER                = 61;  // カウンター
    public const T_XChrStatId ABILITY_COUNTER2               = 62;  // カウンター２
    public const T_XChrStatId ABILITY_DARK                   = 63;  // 暗黒剣
    public const T_XChrStatId ABILITY_AP2                    = 64;  // ＡＰ２倍
    public const T_XChrStatId ABILITY_EXP2                   = 65;  // ＥＸＰ２倍
    public const T_XChrStatId ABILITY_BOOSTER                = 66;  // ブースター
    public const T_XChrStatId ABILITY_MAGIC_COUNTER          = 67;  // 魔法カウンター
    public const T_XChrStatId ABILITY_MEDICINE               = 68;  // くすりのちしき
    public const T_XChrStatId ABILITY_AUTO_POTION            = 69;  // オートポーション
    public const T_XChrStatId ABILITY_AUTO_CUREALL           = 70;  // オート万能薬
    public const T_XChrStatId ABILITY_AUTO_PHENIX            = 71;  // オートフェニックス
    public const T_XChrStatId ABILITY_LIMITUP                = 72;  // リミットアップ
    public const T_XChrStatId ABILITY_DREAM                  = 73;  // 夢オチ
    public const T_XChrStatId ABILITY_PIERCE                 = 74;  // かんつう
    public const T_XChrStatId ABILITY_EXCHANGE               = 75;  // 自動交代
    public const T_XChrStatId ABILITY_HP_RECOVER             = 76;  // 歩くとＨＰ回復
    public const T_XChrStatId ABILITY_MP_RECOVER             = 77;  // 歩くとＭＰ回復
    public const T_XChrStatId ABILITY_NONENCOUNT             = 78;  // エンカウントなし
    public const T_XChrStatId STAT_DEATH_PATTERN             = 79;  // 死にパターン
    public const T_XChrStatId STAT_EVENT_CHR                 = 80;  // イベントキャラクターフラグ
    public const T_XChrStatId STAT_ACTION                    = 81;  // 行動フラグ
    public const T_XChrStatId STAT_CURSOR                    = 82;  // カーソルフラグ
    public const T_XChrStatId STAT_CTB_LIST                  = 83;  // CTB リストフラグ
    public const T_XChrStatId STAT_VISIBLE                   = 84;  // 表示フラグ
    public const T_XChrStatId STAT_MOVE_AREA                 = 85;  // 移動エリア
    public const T_XChrStatId STAT_MOVE_POS                  = 86;  // 移動位置
    public const T_XChrStatId STAT_EFFLV                     = 87;  // エフェクトレベル
    public const T_XChrStatId STAT_MODEL                     = 88;  // モデルフラグ
    public const T_XChrStatId STAT_DAMAGE_CHR                = 89;  // ダメージを受けるキャラクター
    public const T_XChrStatId STAT_MOVE_TARGET               = 90;  // 移動ターゲットキャラクター
    public const T_XChrStatId STAT_MOTIONLV                  = 91;  // モーションレベル
    public const T_XChrStatId STAT_NOP                       = 92;  // なし
    public const T_XChrStatId STAT_MOVE_FLAG                 = 93;  // 移動フラグ
    public const T_XChrStatId STAT_LIVE_MOTION               = 94;  // 行き返りモーション
    public const T_XChrStatId STAT_ADJUST_POS                = 95;  // 微調整位置フラグ
    public const T_XChrStatId STAT_HEIGHT_ON                 = 96;  // 高さオンフラグ
    public const T_XChrStatId STAT_SLEEP_RECOVER_FLAG        = 97;  // 眠りからの復活フラグ
    public const T_XChrStatId STAT_ABS_FIRE                  = 98;  // 吸収属性 炎
    public const T_XChrStatId STAT_ABS_COLD                  = 99;  // 吸収属性 冷気
    public const T_XChrStatId STAT_ABS_THUNDER               = 100; // 吸収属性 雷
    public const T_XChrStatId STAT_ABS_WATER                 = 101; // 吸収属性 水
    public const T_XChrStatId STAT_ABS_HOLY                  = 102; // 吸収属性 聖
    public const T_XChrStatId STAT_INV_FIRE                  = 103; // 無効属性 炎
    public const T_XChrStatId STAT_INV_COLD                  = 104; // 無効属性 冷気
    public const T_XChrStatId STAT_INV_THUNDER               = 105; // 無効属性 雷
    public const T_XChrStatId STAT_INV_WATER                 = 106; // 無効属性 水
    public const T_XChrStatId STAT_INV_HOLY                  = 107; // 無効属性 聖
    public const T_XChrStatId STAT_HALF_FIRE                 = 108; // 半減属性 炎
    public const T_XChrStatId STAT_HALF_COLD                 = 109; // 半減属性 冷気
    public const T_XChrStatId STAT_HALF_THUNDER              = 110; // 半減属性 雷
    public const T_XChrStatId STAT_HALF_WATER                = 111; // 半減属性 水
    public const T_XChrStatId STAT_HALF_HOLY                 = 112; // 半減属性 聖
    public const T_XChrStatId STAT_WEAK_FIRE                 = 113; // 弱点属性 炎
    public const T_XChrStatId STAT_WEAK_COLD                 = 114; // 弱点属性 冷気
    public const T_XChrStatId STAT_WEAK_THUNDER              = 115; // 弱点属性 雷
    public const T_XChrStatId STAT_WEAK_WATER                = 116; // 弱点属性 水
    public const T_XChrStatId STAT_WEAK_HOLY                 = 117; // 弱点属性 聖
    public const T_XChrStatId STAT_ADJUST_POS_FLAG           = 118; // 位置調整フラグ
    public const T_XChrStatId STAT_INV_PHYSIC_MOTION         = 119; // 物理無効モーションフラグ
    public const T_XChrStatId STAT_INV_MAGIC_MOTION          = 120; // 魔法無効モーションフラグ
    public const T_XChrStatId STAT_STEAL_COUNT               = 121; // 盗まれカウント
    public const T_XChrStatId STAT_WAIT_MOTION_FLAG          = 122; // 待機モーションフラグ
    public const T_XChrStatId STAT_ATTACK_RETURN_FLAG        = 123; // 攻撃帰りフラグ
    public const T_XChrStatId STAT_ATTACK_NORMAL_FRAME       = 124; // 攻撃フレーム数：通常
    public const T_XChrStatId STAT_DISABLE_MOVE_FLAG         = 125; // 移動不可フラグ
    public const T_XChrStatId STAT_DISABLE_JUMP_FLAG         = 126; // ジャンプ不可フラグ
    public const T_XChrStatId STAT_BODYHIT_FLAG              = 127; // 体の当たり判定
    public const T_XChrStatId STAT_EFFVAR                    = 128; // エフェクト変数
    public const T_XChrStatId STAT_ITEM                      = 129; // 盗めるアイテム
    public const T_XChrStatId STAT_ITEM_NUM                  = 130; // 盗めるアイテム数
    public const T_XChrStatId STAT_RAREITEM                  = 131; // 盗めるレアアイテム
    public const T_XChrStatId STAT_RAREITEM_NUM              = 132; // 盗めるレアアイテム数
    public const T_XChrStatId STAT_MAGICLV                   = 133; // 魔法レベル
    public const T_XChrStatId STAT_APPEAR_MOTION_FLAG        = 134; // 出現フラグ
    public const T_XChrStatId STAT_CURSOR_ELEMENT            = 135; // カーソルエレメント
    public const T_XChrStatId STAT_LIMIT_BAR_FLAG_CAM        = 136; // リミットバーフラグ：カメラ用
    public const T_XChrStatId STAT_LIMIT_BAR_FLAG            = 137; // リミットバーフラグ
    public const T_XChrStatId STAT_DROP1                     = 138; // 通常アイテム１落とす確率
    public const T_XChrStatId STAT_DROP2                     = 139; // 通常アイテム２落とす確率
    public const T_XChrStatId STAT_WEAPON_DROP               = 140; // 武器落とす確率
    public const T_XChrStatId STAT_STEAL                     = 141; // 盗む確率
    public const T_XChrStatId STAT_EXIST_FLAG                = 142; // 存在フラグ
    public const T_XChrStatId STAT_LIVE                      = 143; // ライブラ
    public const T_XChrStatId STAT_STR_MEMORY                = 144; // 力の記憶
    public const T_XChrStatId STAT_MAG_MEMORY                = 145; // 魔力の記憶
    public const T_XChrStatId STAT_DEX_MEMORY                = 146; // すばやさの記憶
    public const T_XChrStatId STAT_MOVE_MEMORY               = 147; // 移動の記憶
    public const T_XChrStatId STAT_ABILITY_MEMORY            = 148; // アビリティーの記憶
    public const T_XChrStatId STAT_DODGE                     = 149; // よける
    public const T_XChrStatId STAT_DEFEND                    = 150; // まもる
    public const T_XChrStatId STAT_BLOW                      = 151; // 吹き飛ばし
    public const T_XChrStatId STAT_RELIFE                    = 152; // リレイズ
    public const T_XChrStatId STAT_CURSE                     = 153; // カーズ
    public const T_XChrStatId STAT_DEFENSE                   = 154; // ぼうぎょ
    public const T_XChrStatId STAT_PROTECT                   = 155; // かばう
    public const T_XChrStatId STAT_IRON                      = 156; // てっぺき
    public const T_XChrStatId STAT_DEATH_SENTENCE            = 157; // 死の宣告
    public const T_XChrStatId STAT_MOTION_TYPE               = 158; // モーションタイプ
    public const T_XChrStatId STAT_DEATH_SENTENCE_START      = 159; // 死の宣告：初期値
    public const T_XChrStatId STAT_DEATH_SENTENCE_COUNT      = 160; // 死の宣告：カウント
    public const T_XChrStatId STAT_DMG_DIR                   = 161; // ダメージ方向
    public const T_XChrStatId STAT_DIRECTION_CHANGE_FLAG     = 162; // 方向チェックフラグ
    public const T_XChrStatId STAT_DIRECTION_CHANGE_EFFECT   = 163; // 方向変更有効フラグ
    public const T_XChrStatId STAT_DIRECTION_FIX_FLAG        = 164; // 方向固定フラグ
    public const T_XChrStatId STAT_HIT_TERMINATE_FLAG        = 165; // ヒット終了フラグ
    public const T_XChrStatId STAT_DAMAGE_HP                 = 166; // ＨＰダメージ
    public const T_XChrStatId STAT_DAMAGE_MP                 = 167; // ＭＰダメージ
    public const T_XChrStatId STAT_DAMAGE_CTB                = 168; // ＣＴＢダメージ
    public const T_XChrStatId STAT_APPEAR_INVISIBLE_FLAG     = 169; // 出現時見えないフラグ
    public const T_XChrStatId STAT_EFFECT_HIT_NUM            = 170; // ヒットエフェクト番号
    public const T_XChrStatId STAT_AVOID_FLAG                = 171; // 避けフラグ
    public const T_XChrStatId STAT_BLOW_EXIST_FLAG           = 172; // 吹き飛ばし存在フラグ
    public const T_XChrStatId STAT_ESCAPE_FLAG               = 173; // 逃げるフラグ
    public const T_XChrStatId STAT_HIDE                      = 174; // ハイド
    public const T_XChrStatId STAT_DEF_DEATH                 = 175; // 防御：戦闘可能
    public const T_XChrStatId STAT_DEF_ZOMBIE                = 176; // 防御：ゾンビ
    public const T_XChrStatId STAT_DEF_STONE                 = 177; // 防御：石化
    public const T_XChrStatId STAT_DEF_POISON                = 178; // 防御：毒
    public const T_XChrStatId STAT_DEF_POWER_BREAK           = 179; // 防御：パワーブレイク
    public const T_XChrStatId STAT_DEF_MAGIC_BREAK           = 180; // 防御：マジックブレイク
    public const T_XChrStatId STAT_DEF_ARMOR_BREAK           = 181; // 防御：アーマーブレイク
    public const T_XChrStatId STAT_DEF_MENTAL_BREAK          = 182; // 防御：メンタルブレイク
    public const T_XChrStatId STAT_DEF_CONFUSE               = 183; // 防御：こんらん
    public const T_XChrStatId STAT_DEF_BERSERK               = 184; // 防御：バーサク
    public const T_XChrStatId STAT_DEF_PROV                  = 185; // 防御：挑発
    public const T_XChrStatId STAT_DEF_THREAT                = 186; // 防御：威嚇
    public const T_XChrStatId STAT_DEF_SLEEP                 = 187; // 防御：睡眠
    public const T_XChrStatId STAT_DEF_SILENCE               = 188; // 防御：沈黙
    public const T_XChrStatId STAT_DEF_DARK                  = 189; // 防御：暗闇
    public const T_XChrStatId STAT_DEF_SHELL                 = 190; // 防御：シェル
    public const T_XChrStatId STAT_DEF_PROTESS               = 191; // 防御：プロテス
    public const T_XChrStatId STAT_DEF_REFLECT               = 192; // 防御：リフレク
    public const T_XChrStatId STAT_DEF_BAWATER               = 193; // 防御：バウォタ
    public const T_XChrStatId STAT_DEF_BAFIRE                = 194; // 防御：バファイ
    public const T_XChrStatId STAT_DEF_BATHUNDER             = 195; // 防御：バサンダ
    public const T_XChrStatId STAT_DEF_BACOLD                = 196; // 防御：バコルド
    public const T_XChrStatId STAT_DEF_REGEN                 = 197; // 防御：リジェネ
    public const T_XChrStatId STAT_DEF_HASTE                 = 198; // 防御：へースト
    public const T_XChrStatId STAT_DEF_SLOW                  = 199; // 防御：スロウ
    public const T_XChrStatId STAT_DEF_LIVE                  = 200; // 防御：ライブラ
    public const T_XChrStatId STAT_DEF_STR_MEMORY            = 201; // 防御：力の記憶
    public const T_XChrStatId STAT_DEF_MAG_MEMORY            = 202; // 防御：魔力の記憶
    public const T_XChrStatId STAT_DEF_DEX_MEMORY            = 203; // 防御：すばやさの記憶
    public const T_XChrStatId STAT_DEF_MOVE_MEMORY           = 204; // 防御：移動の記憶
    public const T_XChrStatId STAT_DEF_ABILITY_MEMORY        = 205; // 防御：アビリティーの記憶
    public const T_XChrStatId STAT_DEF_DODGE                 = 206; // 防御：よける
    public const T_XChrStatId STAT_DEF_DEFEND                = 207; // 防御：まもる
    public const T_XChrStatId STAT_DEF_RELIFE                = 208; // 防御：リレイズ
    public const T_XChrStatId STAT_DEF_BLOW                  = 209; // 防御：吹き飛ばし
    public const T_XChrStatId STAT_DEF_CURSE                 = 210; // 防御：カーズ
    public const T_XChrStatId STAT_DEF_DEFENSE               = 211; // 防御：ぼうぎょ
    public const T_XChrStatId STAT_DEF_PROTECT               = 212; // 防御：かばう
    public const T_XChrStatId STAT_DEF_IRON                  = 213; // 防御：てっぺき
    public const T_XChrStatId STAT_DEF_DEATH_SENTENCE        = 214; // 防御：死の宣告
    public const T_XChrStatId STAT_HP_LIST                   = 215; // ＨＰリスト表示
    public const T_XChrStatId STAT_VISIBLE_CAM               = 216; // カメラ用表示フラグ
    public const T_XChrStatId STAT_VISIBLE_OUT               = 217; // バトル終了時の表示フラグ
    public const T_XChrStatId STAT_ROUND                     = 218; // 指定方向フレーム
    public const T_XChrStatId STAT_ROUND_RETURN              = 219; // 基本方向フレーム
    public const T_XChrStatId STAT_WIN_POSE                  = 220; // 勝利のポーズ
    public const T_XChrStatId STAT_VIGOR                     = 221; // 元気状態
    public const T_XChrStatId STAT_FAST_MODEL_FLAG           = 222; // 速いモデルフラグ
    public const T_XChrStatId STAT_ALIVE_NOT_STONE           = 223; // 生きていて石化でないとき
    public const T_XChrStatId STAT_COMMAND_TYPE              = 224; // コマンドタイプ
    public const T_XChrStatId STAT_EFFECT_TARGET_FLAG        = 225; // エフェクトターゲットフラグ
    public const T_XChrStatId STAT_MAGIC_EFFECT_GROUND       = 226; // 地上：魔法エフェクト番号
    public const T_XChrStatId STAT_MAGIC_EFFECT_WATER        = 227; // 水中：魔法エフェクト番号
    public const T_XChrStatId STAT_IDLE2_PROB                = 228; // idle2 の確率
    public const T_XChrStatId STAT_ATTACK_MOTION_TYPE        = 229; // 攻撃モーションタイプ
    public const T_XChrStatId STAT_ATTACK_INC_SPEED          = 230; // 攻撃：加速％
    public const T_XChrStatId STAT_ATTACK_DEC_SPEED          = 231; // 攻撃：減速％
    public const T_XChrStatId STAT_CTB                       = 232; // ＣＴＢ値
    public const T_XChrStatId STAT_APPEAR_COUNT              = 233; // 出現カウント
    public const T_XChrStatId STAT_MOTION_NUM                = 234; // モーション補間番号
    public const T_XChrStatId STAT_INFO_MES_ID               = 235; // 情報：メッセージＩＤ
    public const T_XChrStatId STAT_LIVE_MES_ID               = 236; // ライブラ：メッセージＩＤ
    public const T_XChrStatId STAT_VISIBLE_EFF               = 237; // エフェクト用表示フラグ
    public const T_XChrStatId STAT_MOTION_DISPOSE_FLAG       = 238; // モーション解放フラグ
    public const T_XChrStatId STAT_MODEL_DISPOSE_FLAG        = 239; // モデル解放フラグ
    public const T_XChrStatId STAT_DEF_CTB                   = 240; // CTB 防御
    public const T_XChrStatId STAT_SHADOW                    = 241; // 影
    public const T_XChrStatId STAT_DEATH                     = 242; // 死亡
    public const T_XChrStatId STAT_DEATH_STONE               = 243; // 死亡か石化
    public const T_XChrStatId STAT_CHECK_POS                 = 244; // 立ち位置から外れているかチェック
    public const T_XChrStatId STAT_WIN_SE                    = 245; // 勝利のＳＥ
    public const T_XChrStatId STAT_ATTACK_NUM                = 246; // 攻撃回数
    public const T_XChrStatId STAT_NEAR_MOTION               = 247; // 近距離モーション
    public const T_XChrStatId STAT_TALK_STAT1                = 248; // 喋れる状態１
    public const T_XChrStatId STAT_TALK_STAT2                = 249; // 喋れる状態２
    public const T_XChrStatId STAT_NEAR_MOTION_SET           = 250; // 近距離攻撃強制設定
    public const T_XChrStatId STAT_MOTION_SPEED_NORMAL       = 251; // 通常モーションスピード
    public const T_XChrStatId STAT_MOTION_SPEED_NORMAL_START = 252; // 通常モーションスピード：モーション開始時
    public const T_XChrStatId STAT_OWN_ATTACK_NEAR           = 253; // 自分攻撃近距離フラグ
    public const T_XChrStatId STAT_TALK_STAT3                = 254; // 喋れる状態３
    public const T_XChrStatId STAT_COMMAND_SET               = 255; // コマンド設定可能状態
    public const T_XChrStatId STAT_PROV_COMMAND_FLAG         = 256; // 挑発を自分で判断するフラグ
    public const T_XChrStatId STAT_PROV_CHR                  = 257; // 挑発された相手
    public const T_XChrStatId STAT_USE_MP0                   = 258; // 使用ＭＰ０
    public const T_XChrStatId STAT_ICON_NUMBER               = 259; // アイコン番号
    public const T_XChrStatId STAT_SOUND_HIT_NUM             = 260; // ヒットＳＥ番号
    public const T_XChrStatId STAT_DAMAGE_NUM_POS            = 261; // ダメージ数値位置
    public const T_XChrStatId STAT_SUMMONER                  = 262; // 召喚者番号
    public const T_XChrStatId STAT_SP_INVINCIBLE             = 263; // 無敵
    public const T_XChrStatId STAT_SP_INV_MAGIC              = 264; // 魔法無効
    public const T_XChrStatId STAT_SP_INV_PHYSIC             = 265; // 物理無効
    public const T_XChrStatId STAT_BLUE_MAGIC                = 266; // 青魔法
    public const T_XChrStatId STAT_SP_DISABLE_ZAN            = 267; // 斬魔刀で切れない
    public const T_XChrStatId STAT_OVER_KILL_HP              = 268; // オーバーキルＨＰ
    public const T_XChrStatId STAT_RETURN_MOTION_TYPE        = 269; // 戻りモーションタイプ
    public const T_XChrStatId STAT_CAM_WIDTH                 = 270; // カメラの太さ
    public const T_XChrStatId STAT_CAM_HEIGHT                = 271; // カメラの高さ
    public const T_XChrStatId STAT_HEIGHT                    = 272; // 高さ
    public const T_XChrStatId STAT_YOUJINBO                  = 273; // ようじんぼうとの相性
    public const T_XChrStatId STAT_PAYMENT                   = 274; // ようじんぼうへの支払い額
    public const T_XChrStatId STAT_MONSTER_VALUE_MAX         = 275; // モンスター係数：最大
    public const T_XChrStatId STAT_COMMAND_EXE_COUNT         = 276; // コマンド実行回数
    public const T_XChrStatId STAT_CONSENT                   = 277; // 納得フラグ
    public const T_XChrStatId STAT_ATTACK_NEAR_FRAME         = 278; // 攻撃フレーム数：近距離
    public const T_XChrStatId STAT_ENERGY                    = 279; // メーガスやる気
    public const T_XChrStatId STAT_LIMIT_GAUGE_ADD           = 280; // リミットゲージ加算
    public const T_XChrStatId STAT_HP_HALF                   = 281; // ＨＰ半分以下チェック
    public const T_XChrStatId STAT_LIMIT_GAUGE_CHECK         = 282; // リミットゲージチェック
    public const T_XChrStatId STAT_HP_CHECK                  = 283; // ＨＰが満タンかチェック
    public const T_XChrStatId STAT_MP_CHECK                  = 284; // ＭＰが満タンかチェック
    public const T_XChrStatId STAT_BA_ALL_CHECK              = 285; // バ系が全てかかっているかをチェック
    public const T_XChrStatId STAT_SHELL_REFLECT             = 286; // シェルかリフレクがかかっている
    public const T_XChrStatId STAT_PROTESS_REFLECT           = 287; // プロテスかリフレクがかかっている
    public const T_XChrStatId STAT_HASTE_REFLECT             = 288; // ヘイストかリフレクがかかっている
    public const T_XChrStatId STAT_WEAK_MOTION               = 289; // 弱りモーションの取得
    public const T_XChrStatId STAT_SP_WAIRO                  = 290; // わいろ
    public const T_XChrStatId STAT_ATTACK_MOTION_FRAME       = 291; // 攻撃通常フレーム数
    public const T_XChrStatId STAT_MOTION_TYPE_RESET         = 292; // モーションタイプリセット
    public const T_XChrStatId STAT_MOTION_TYPE_ADD           = 293; // モーションタイプ追加
    public const T_XChrStatId STAT_DEATH_STATUS              = 294; // 死亡ステータス
    public const T_XChrStatId STAT_TARGET_LIST               = 295; // ターゲットリストフラグ
    public const T_XChrStatId STAT_LIMIT_BAR_POS             = 296; // リミットバー位置
    public const T_XChrStatId STAT_CENTER_CHR_FLAG           = 297; // 中央キャラフラグ
    public const T_XChrStatId STAT_SAME_TARGET_CHECK         = 298; // 同じターゲットチェック
    public const T_XChrStatId STAT_GET_AP                    = 299; // 獲得：ＡＰ値
    public const T_XChrStatId STAT_GET_OVER_AP               = 300; // 獲得：オーバーキルＡＰ値
    public const T_XChrStatId STAT_GET_GILL                  = 301; // 獲得：ギル
    public const T_XChrStatId STAT_STR_UP                    = 302; // 力　　　：調整値
    public const T_XChrStatId STAT_VIT_UP                    = 303; // 体力　　：調整値
    public const T_XChrStatId STAT_MAG_UP                    = 304; // 魔力　　：調整値
    public const T_XChrStatId STAT_SPIRIT_UP                 = 305; // 精神　　：調整値
    public const T_XChrStatId STAT_DEX_UP                    = 306; // すばやさ：調整値
    public const T_XChrStatId STAT_LUCK_UP                   = 307; // 運　　　：調整値
    public const T_XChrStatId STAT_AVOID_UP                  = 308; // 回避率　：調整値
    public const T_XChrStatId STAT_HIT_UP                    = 309; // 命中率　：調整値
    public const T_XChrStatId STAT_USE_MP                    = 310; // 使用ＭＰ値
    public const T_XChrStatId STAT_USE_LIMIT                 = 311; // 使用リミット値
    public const T_XChrStatId STAT_USE_LIMIT_ALL             = 312; // 使用リミット全フラグ
    public const T_XChrStatId STAT_CONTINUE_MAGIC            = 313; // 連続魔法使用フラグ
    public const T_XChrStatId STAT_ITEM1_COM                 = 314; // 落とすアイテム１：コモン
    public const T_XChrStatId STAT_ITEM1_RARE                = 315; // 落とすアイテム１：レア
    public const T_XChrStatId STAT_ITEM2_COM                 = 316; // 落とすアイテム２：コモン
    public const T_XChrStatId STAT_ITEM2_RARE                = 317; // 落とすアイテム２：レア
    public const T_XChrStatId STAT_ITEM1_COM_OVER_KILL       = 318; // 落とすアイテム１：コモン：オーバーキル用
    public const T_XChrStatId STAT_ITEM1_RARE_OVER_KILL      = 319; // 落とすアイテム１：レア：オーバーキル用
    public const T_XChrStatId STAT_ITEM2_COM_OVER_KILL       = 320; // 落とすアイテム２：コモン：オーバーキル用
    public const T_XChrStatId STAT_ITEM2_RARE_OVER_KILL      = 321; // 落とすアイテム２：レア：オーバーキル用
    public const T_XChrStatId STAT_ITEM1_COM_NUM             = 322; // 落とすアイテム１：コモン：数
    public const T_XChrStatId STAT_ITEM1_RARE_NUM            = 323; // 落とすアイテム１：レア：数
    public const T_XChrStatId STAT_ITEM2_COM_NUM             = 324; // 落とすアイテム２：コモン：数
    public const T_XChrStatId STAT_ITEM2_RARE_NUM            = 325; // 落とすアイテム２：レア：数
    public const T_XChrStatId STAT_ITEM1_COM_OVER_KILL_NUM   = 326; // 落とすアイテム１：コモン：オーバーキル用：数
    public const T_XChrStatId STAT_ITEM1_RARE_OVER_KILL_NUM  = 327; // 落とすアイテム１：レア：オーバーキル用：数
    public const T_XChrStatId STAT_ITEM2_COM_OVER_KILL_NUM   = 328; // 落とすアイテム２：コモン：オーバーキル用：数
    public const T_XChrStatId STAT_ITEM2_RARE_OVER_KILL_NUM  = 329; // 落とすアイテム２：レア：オーバーキル用：数
    public const T_XChrStatId STAT_DEATH_RETURN              = 330; // 死亡帰りフラグ
    public const T_XChrStatId STAT_LINEAR_MOVE_RESET         = 331; // 直線移動リセット
    public const T_XChrStatId STAT_BODYHIT_DIRECT            = 332; // 直接ボディヒット設定
    public const T_XChrStatId STAT_JOIN                      = 333; // 仲間になっている
    public const T_XChrStatId STAT_ETERNAL_RELIFE            = 334; // 永久リライフ
    public const T_XChrStatId STAT_NECK_TARGET_FLAG          = 335; // 首ターゲットなし
    public const T_XChrStatId STAT_VISIBLE_OUT_ON            = 336; // バトル終了時表示フラグ
    public const T_XChrStatId STAT_REGEN_DAMAGE_FLAG         = 337; // リジェネダメージを画面内に入れるフラグ
    public const T_XChrStatId STAT_NUM_PRINT_ELEMENT         = 338; // 番号表示エレメント
}