name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .\Fahrenheit.slnx

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: release

# The permissions block is no longer required as explicit PAT is used for NuGet auth;
# and releases are no longer made on GitHub actions, but locally with ci-release.ps1

jobs:
  build:
    runs-on: windows-2025

    steps:
    - name: Print runner environment
      run: env
    
    - name: Checkout
      uses: actions/checkout@v7
      with:
        submodules: 'recursive'

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v3

    - name: Bootstrap vcpkg
      shell: pwsh
      run: |
        cd "$VCPKG_INSTALLATION_ROOT"      
        bootstrap-vcpkg.bat -disableMetrics
        
    - name: Integrate vcpkg
      shell: pwsh
      run: |
        cd "$VCPKG_INSTALLATION_ROOT"      
        vcpkg integrate install

      # Compensate for https://github.com/NuGet/Home/issues/14113
    - name: Restore NuGet packages
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: msbuild /m /p:ContinuousIntegrationBuild=true /p:Configuration=${{ env.BUILD_CONFIGURATION }} /t:Restore ${{ env.SOLUTION_FILE_PATH }}

      # 11/06/26 - publish is now implicit as part of build
    - name: Build
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      # Force deterministic build per https://github.com/clairernovotny/DeterministicBuilds
      run: msbuild /m /p:ContinuousIntegrationBuild=true /p:Configuration=${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_FILE_PATH }}
